### ISSUE TITLE
Better document tombstones, delete_mode and MDC [JIRA: PMT-166]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1007]
Relevant mailing list thread and resources:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-April/015062.html

http://docs.basho.com/riak/latest/ops/advanced/configs/configuration-files/

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2011-October/006048.html

**Comment by DSomogyi** [comment]
Comment for Jira.
