### ISSUE TITLE
Open Files Limit Page [JIRA: PMT-165]

### ISSUE THREAD

**Issue by matthewvon** [basho/basho_docs#1030]
I would like to open a two point discussion regarding this page:

http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/
1.  from 1.4 forward, it would be safer if open files limit recommendation was 128000 (twice the current 64000).  I can hit the 64000 limit with a 2 billion key load to a single server running leveldb with AAE active.
2. I am unclear as to what the user should or should not do in the sysctl discussion in the Linux section.  The current file-max limit in Linux 2.6 and 3.2 kernels is over 3 million for a 32G machine.  Having user continue with number lower than our recommend 128000 would be bad.  But this is not the discussion I see written.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by Basho-JIRA** [comment]
At some point, OFL page, https://docs.basho.com/riak/kv/2.2.0/using/performance/open-files-limit/,  was updated to recommend: `ulimit -n 200000`  

***[posted via JIRA by Lauren Rother]***
