### ISSUE TITLE
Descrepancy between leveldb parameter planning page and memory model spread sheet [JIRA: PMT-164]

### ISSUE THREAD

**Issue by shino** [basho/basho_docs#1032]
There are some difference between leveldb parameter planning [1] and
spreadsheet [2] linked from the page.
The spreadsheet seems to fit the README of leveldb at 1.4 branch [3].

Differences are in Step 3 and 4.
If the spreadsheet is correct, the calculation in Step3 will be
`(max_open_files-10) * 4MB` and
Step4 will be "the sum of `write_buffer_size_min` and `write_buffer_size_max`
instead of "the average".

[1] http://docs.basho.com/riak/latest/ops/advanced/backends/leveldb/#Parameter-Planning
[2] https://github.com/basho/basho_docs/raw/master/source/data/leveldb_sizing_1.4.xls
[3] https://github.com/basho/leveldb/blob/1.4/README#L39

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
@shino Hi! I am sorry this issue has been open for so long. Is this issue still very important for users to know right now?

**Comment by shino** [comment]
@laurenrother Thanks for notification.
Leveldb tuning parameters were totally changed  at riak 2.0. So I think this issue is is almost irrelevant. Close.
