### ISSUE TITLE
HAProxy + SSL [JIRA: PMT-163]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1042]
The HAProxy documentation should make a recommendation that HAProxy be used as the SSL endpoint, and not proxy requests to Riak nodes using SSL. This setup can cause issues.

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-April/015150.html

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
@lukebakken What's the priority on this issue?

**Comment by lukebakken** [comment]
Oh I'd say very very low, especially since HTTP is not supported via clients in 2.0.

**Comment by laurenrother** [comment]
I wish we could've gotten this in before we closed 1.4 to updates, but we didn't. :T
