### ISSUE TITLE
Create HOTWTO for destructive OS upgrades without losing data using `replace` [JIRA: PMT-160]

### ISSUE THREAD

**Issue by angrycub** [basho/basho_docs#1092]
Based on ZD ticket #7939

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
@angrycub Since this ticket was opened awhile ago, what's your priority recommendation for it?

**Comment by angrycub** [comment]
@laurenrother I don't think it's a high priority document.  It's intuitive once you know how replace functions in a cluster.  However, it does serve as a vehicle to inform users that there are ways to do what appear to be destructive operations in a cluster without losing data by operating temporarily with reduced replicas

**Comment by laurenrother** [comment]
I'm gonna close this as it will naturally get covered by the content reorg/spruce up project. :tangerine:
