### ISSUE TITLE
No documentation for n_val_1_get_requests

### ISSUE THREAD

**Issue by jmshoffs0812** [basho/basho_docs#1112]
Recent support concerns have brought to light that there is no documentation for the Riak CS setting, n_val_1_get_requests.

**Comment by binarytemple** [comment]
@laurenrother interestingly, this information seems to have vanished again.

**Comment by binarytemple** [comment]
@laurenrother correction. it can now be found [here](http://docs.basho.com/riakcs/2.0.0beta1/cookbooks/configuration/Configuring-Riak-CS/#Other-Riak-CS-Settings)
