### ISSUE TITLE
Erlang R15B01 + SHA256 in SSL certificate [JIRA: PMT-159]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1145]
Erlang R15B02 added support for SHA256 hashing:

http://www.erlang.org/download/otp_src_R15B02.readme

Since Riak ships with R15B01, we should note to use a different hash function for your certificates.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
@lukebakken Hi there! What's the priority on this documentation?

**Comment by lukebakken** [comment]
Super duper duper low, esp since Riak 2.0 and beyond doesn't have this issue.

**Comment by laurenrother** [comment]
Same as a previous issue... it'd have been nice if we'd gotten to this before 1.4 was closed to additions, but we didn't. :T
