### ISSUE TITLE
Document sloppy_quorum options [JIRA: PMT-157]

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#1225]
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_get_fsm.erl#L48

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
@macintux I'm looking for priority recommendations on these docs, too. :)

**Comment by laurenrother** [comment]
Due to super low priority, abundance of issues, age of ticket, and upcoming content rework, I'm closing this issue.
