### ISSUE TITLE
Missing Documentation for HTTP mapreduce

### ISSUE THREAD

**Issue by pgaultier** [basho/basho_docs#1340]
We are trying to use the http map reduce ap in Riak 2.0.

Everything works as expected except when we try to use "typed buckets". The documentation does not explain how to use "typed buckets" as input for http mapreduce.

We tried several input formats without any luck.

Can someone upgrade the HTTP Api part of the documention to match 2.0 features ?

**Comment by lucperkins** [comment]
This and other MapReduce issues will be addressed in PR #1520
