### ISSUE TITLE
fields not described for repl stats "overload_drops" & "source_drops"

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#1367]
EMEA CSE had a zendest ticket #8858 come in requesting more detailed information about three fields in the repl stats:
`realtime_queue_stats.consumers.<clustername>.drops`
`realtime_queue_stats.overload_drops`
`sinks.sink_stats.rt_sink_connected_to.source_drops`

The latter two don't appear to be documented as of now. We can do so quite quickly by utilizing the research and wording in the ticket response:
https://basho.zendesk.com/agent/#/tickets/8858

**Comment by lucperkins** [comment]
This doc needs some more significant work. For now, I've added the missing items and will follow up with significant EE work soon.
