### ISSUE TITLE
revisit or create an upgrade checklist [JIRA: PMT-156]

### ISSUE THREAD

**Issue by randysecrist** [basho/basho_docs#1427]
The current checklist under the ops/upgrading section is really more for moving development clusters into production.

http://docs.basho.com/riak/latest/ops/upgrading/production-checklist/

We should consider moving that under ops/tuning, and creating a more narrow document that outlines what the items are for just doing upgrades from 1.x to 2.x.

**Comment by lucperkins** [comment]
@randysecrist To kick off that discussion, what would need to be in that document that isn't here? http://docs.basho.com/riak/latest/upgrade-v20

(This is a non-rhetorical question, by the way)

**Comment by randysecrist** [comment]
Taking a look...

In the section for the allow_mult changes...

We ran into an issue where an existing customer which had relied upon the old default behavior of allow_mult=false had to specifically set this for each bucket after an upgrade.  (Not just new ones).  Could we explicitly state that if this property has not been set before, it now needs to be explicitly set to avoid the new default.  We also may want to suggest how to set this property, either via command line or in application startup code.  (See zendesk ticket 9794) for more background.  I'd include the link, but this is public.

Rest of the document looks good.  We probably don't need to state the rolling update process here, as that could be more of a service.

One thing, as part of some research - we also found this script.

https://github.com/basho/bitcask/blob/develop/priv/scripts/downgrade_bitcask.erl

It may be handy to include this when discussing how to rollback from 2.0 into 1.4 should a customer find this necessary.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by Basho-JIRA** [comment]
Awhile back we added: http://docs.basho.com/riak/kv/2.2.3/setup/upgrading/version/#components-that-complicate-downgrades which accounts for most of what was requested in this ticket.

Ran this past Randy, who agreed. 

***[posted via JIRA by Lauren Rother]***
