### ISSUE TITLE
Riak CS Monitoring page missing some guidance

### ISSUE THREAD

**Issue by roooms** [basho/basho_docs#1483]
http://docs.basho.com/riakcs/latest/cookbooks/Monitoring-and-Metrics/

To access the Operational Statistics at `riak-cs/stats` you must sign the request with the admin users access_key and secret_key. Requests that are unsigned will receive an HTTP 500 Internal Server Error.

**Comment by kuenishi** [comment]
Fmmm. Looks like that should be 403, not 500.

**Comment by lucperkins** [comment]
Fixed in commit 17c537b59c5f30add89c52cdd9be75a359335581
