### ISSUE TITLE
Install on Debian 7.x

### ISSUE THREAD

**Issue by areski** [basho/basho_docs#1488]
The instruction on Debian 7.x are misleading to my opinion http://docs.basho.com/riak/latest/ops/building/installing/debian-ubuntu/

Riak will require `libc6` >= 2.15, unfortunately to install a recent version of `libc6` you need to upgrade your system to 'sid', here some info how to:
http://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian

```
#!/bin/sh
echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list
apt-get update
apt-get -t sid install libc6 libc6-dev libc6-dbg
```

It might be good for the community to have clear instructions how to install it properly on Debian 7.x

**Comment by lucperkins** [comment]
@areski Could you possibly review the [accompanying PR](https://github.com/basho/basho_docs/pull/1527)?

**Comment by areski** [comment]
Thanks @lucperkins that seems accurate, and with this new addition it will prevent new comers to not fall in the same trap.

From a technical point of view, I wish we had an other solution, peoples usually choose debian for the stability of the distribution, thus changing it to "testing/unstable" is not something most would like to do.

Thanks for the follow up, feel free to close the ticket.

**Comment by lucperkins** [comment]
@areski Thanks for your help!
