### ISSUE TITLE
ulimit -n command results in error on OS X Yosemite [JIRA: PMT-154]

### ISSUE THREAD

**Issue by mbbroberg** [basho/basho_docs#1493]
The directions for [open file limits](http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/#Mac-OS-X) includes adding the following commands to a `.bashrc` file or similar. This appears to result in an error when added to the file or run manually: 

```
  bash-3.2$ ulimit -n 65536
  bash: ulimit: open files: cannot modify limit: Invalid argument
  bash-3.2$ ulimit -u 2048
  bash: ulimit: max user processes: cannot modify limit: Operation not permitted
```

**Comment by mjbrender** [comment]
This may help: http://yabfog.com/blog/2014/10/22/yosemite-upgrade-changes-open-file-limit

I ran through his recommendation and found `ulimit`no longer errors! :+1:

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by Basho-JIRA** [comment]
I believe this was fixed with https://github.com/basho/basho_docs/pull/2445 

***[posted via JIRA by Eric Johnson]***
