### ISSUE TITLE
Rename 5 minute install -> install from source 

### ISSUE THREAD

**Issue by binarytemple** [basho/basho_docs#1494]
http://docs.basho.com/riak/latest

![screen shot 2015-01-19 at 11 42 31](https://cloud.githubusercontent.com/assets/419046/5799957/7e689f5a-9fd0-11e4-8896-6fd226612e8b.png)

The links, "Why Riak", "Download Riak", and "5 Minute Install" - are images, so I can't just create a PR to change the text. 

Spoken to a lot of people who don't think it's a good title, PM if you get a chance to discuss.

**Comment by gordonguthrie** [comment]
I like the 5 minute install line - when I was learning Riak as a punter it was my goto page...

**Comment by binarytemple** [comment]
I'm talking about commercial non-erlang developers/operators

**Comment by lucperkins** [comment]
I have strong reservations about changing this, but I'm happy to have this discussion. Please reach out to me on HipChat or email. I'm closing here on GitHub for now (as this is not the preferred venue).
