### ISSUE TITLE
how to upload a file to rickcs server ?

### ISSUE THREAD

**Issue by xiaoliuliu2050** [basho/basho_docs#1496]
dear friend 
recently, I installed a rickcs server myself,
then I tried to use the aws s3 interface to upload a file to my rickcs server .

the client side code:
var bucket = new AWS.S3({params: {
        Bucket: 'test-bucket',
        accessKeyId : 'DVJDPQGX8QG3QLR_T-J2',
        secretAccessKey: '6cThOUXOmxHNAlsjyJzE03-Ph2caqIlAiaG7oQ==',
        sslEnabled : false,
         httpOptions  :{proxy :'http://ecs999.eicps.net:8018',xhrWithCredentials :true}
       // endpoint:'http://ecs999.eicps.net:8018'
}});
var params = {Key: file.name, ContentType: file.type, Body: file};
bucket.upload(params, function (err, data) {
                        window.alert("result");
                        results.innerHTML = err ? 'ERROR!' : 'UPLOADED.';
                    })

as a result ,i failed, there is no  response information from the server and the file is not uploaded to the server !

now I  doubt that maybe it is because the limit to The same-origin policy !
so I want to know whether there is a way to confige cors  in the server side ，
or orther ways to solve my problem!

if it is the fault of my client side code,please  correct me !

the best wishes!

**Comment by xiaoliuliu2050** [comment]
comment :  
I used the aws s3 javascript interface in the client side !

**Comment by lucperkins** [comment]
@xiaoliuliu2050 The appropriate venue for a question like this is [the Riak mailing list](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com). I recommend re-posting the question there. Closing.
