### ISSUE TITLE
404 on minor version of Riak 2.0.x MDC repl conf docs

### ISSUE THREAD

**Issue by binarytemple** [basho/basho_docs#1509]
200:
http://docs.basho.com/riakee/2.0.2/cookbooks/Multi-Data-Center-Replication-Configuration/

404:
http://docs.basho.com/riakee/2.0.4/cookbooks/Multi-Data-Center-Replication-Configuration/

version indicated is wrong:
http://docs.basho.com/riakee/latest/cookbooks/Multi-Data-Center-Replication-Configuration/

**Comment by lucperkins** [comment]
I'll investigate and potentially re-deploy those versions. In the meantime, make sure to use `/riak/<version>/ops/mdc/` instead of the `/riakee` endpoint.
