### ISSUE TITLE
Inconsistencies in/between Garbage Collection settings documentation

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#1512]
The two pages in question are the [Configuring Riak CS][0] Garbage Collection Settings subsection, and the [Configuration Reference][1] Garbage Collection subsection.

The former states under the `gc_interval` setting that 
> It is important that you have only _one_ garbage collection daemon running in a cluster at any point in time.

Implicitly contradicting the above, the `initial_gc_delay` says should be used to
> stagger the execution of garbage collection on multiple nodes since there is currently no coordination among Riak CS nodes

The current recommendation is that there only ever be one garbage collection daemon running. That fact should probably be highlighted (moved into a `Note`?), and the `initial_gc_delay` setting should be updated to reflect that it is no longer useful as there should never be multiple nodes running garbage collection daemons.

The [Configuration Reference][1] page just seems to be missing some potential settings. Comparing that list to the Configuring Riak CS page, there are no notes in the reference about `epoch_start`, `initial_gc_delay`, `max_scheduled_delete_manifests`, `gc_batch_size`, or `gc_max_workers`.

[0]: http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Riak-CS/#Garbage-Collection-Settings
[1]: http://docs.basho.com/riakcs/latest/cookbooks/configuration/configuration-reference/#Garbage-Collection

**Comment by lucperkins** [comment]
@kuenishi What's the best way to prevent multiple garbage collection daemons from running? Drew suggested setting `gc_interval` to `infinity` on all nodes except the node that's supposed to run GC, but we were both wondering if there's another way.
