### ISSUE TITLE
Cautionary language about ring resize in Vnodes doc may no longer be necessary

### ISSUE THREAD

**Issue by ssylvester87** [basho/basho_docs#1524]
http://docs.basho.com/riak/latest/theory/concepts/vnodes/

"While Riak has an experimental ring resizing feature that enables you to change the ring size in an active cluster, we do not yet recommend attempting this."

In discussion with Client Services team, it came up that many customers are using it in production and isn't as dangerous or experimental as this language may indicate. As long as there is enough disk space and you keep an eye on transfer limits, there isn't really "risk".

**Comment by lucperkins** [comment]
@ssylvester87 Awaiting confirmation from engineering et al
