### ISSUE TITLE
Apt repository URL contains underscore rather than dash

### ISSUE THREAD

**Issue by ssylvester87** [basho/basho_docs#1528]
http://docs.basho.com/riakcs/latest/cookbooks/installing/Installing-Riak-CS/

The code block containing "PACKAGE_CLOUD_RIAK_CS_DIR=https://packagecloud.io/install/repositories/basho/riak_cs"

Should read:
"PACKAGE_CLOUD_RIAK_CS_DIR=https://packagecloud.io/install/repositories/basho/riak-cs"

**Comment by lucperkins** [comment]
Fixed in commit 07fe32a4bdbf1889f72c021fb72748cb94115ab8
