### ISSUE TITLE
AAE video link broken

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#1532]
http://docs.basho.com/riak/latest/theory/concepts/aae/ includes a link to http://coffee.jtuple.com/video/AAE.html which is currently down. Pinged @jtuple

**Comment by lucperkins** [comment]
I have hidden this link for now (commit 835e4b52769c1334a28491bbab3736bbfc97f1d3). If a working link is provided, swap out the link and uncomment the Markdown.

**Comment by keroro520** [comment]
IT still exists in earlier version doc, like http://docs.basho.com/riak/1.4.12/theory/concepts/aae/#Resources
