### ISSUE TITLE
Unclear that Riak links do not work with non-default bucket types [JIRA: PMT-51]

### ISSUE THREAD

**Issue by mjbrender** [basho/basho_docs#1544]
This arose from follow up on the riak-user list. 

"Yes, this is still a problem, and I raised it here: https://github.com/basho/riak/issues/673. In the mean time we gave up on the links solution for modelling as it doesn’t fit our use case entirely (plus we need security later and links won’t work with that). Either way it wasn’t entirely clear in the docs that Links are not working with non-default bucket types.   This has been addressed though: https://github.com/basho/basho_docs/pull/1506"

I'd like to investigate and address this gap in documentation.

**Comment by kesslerm** [comment]
@mjbrender, can you please check if the changes from PR #1506, in particular 4b5210f843289f9cca0d3a4e5856c3d75d5b5878, address your concerns? It's part of the latest documentation at http://docs.basho.com/riak/2.0.5/dev/using/link-walking/

**Comment by mjbrender** [comment]
@kesslerm it's worth starting there! I'll email the community member and see if he'd like to add more in a PR. :shipit:

**Comment by laurenrother** [comment]
@mjbrender Is this issue still open?

**Comment by mjbrender** [comment]
@laurenrother this can be closed. Cosmin confirmed it's addressed by @kesslerm's PR:

"Thanks, yes, these changes definitely address my concerns. Much appreciated."
