### ISSUE TITLE
RHEL/CentOS install instructions still reference old repo location [JIRA: PMT-151]

### ISSUE THREAD

**Issue by ssylvester87** [basho/basho_docs#1545]
http://docs.basho.com/riak/latest/ops/building/installing/rhel-centos/
^Also any version after 2.0

Instructions further down the page still reference yum.basho.com when the packages have been moved to packagecloud.io.

**Comment by DSomogyi** [comment]
Comment added for Jira.

**Comment by DSomogyi** [comment]
Import to Jira

**Comment by ooshlablu** [comment]
Test

**Comment by Basho-JIRA** [comment]
http://docs.basho.com/riak/kv/2.1.4/setup/installing/rhel-centos/ no longer references yum.basho.com package locations 

***[posted via JIRA by Eric Johnson]***
