### ISSUE TITLE
[Documentaion] broken links in "The Riak API" docs [JIRA: PMT-76]

### ISSUE THREAD

**Issue by iStefo** [basho/basho_docs#1561]
The paragraph on http://docs.basho.com/riak/1.1.0/references/appendices/concepts/#The-Riak-APIs contains broken links. I know that this is an issue of very low priority, but I think it should be said.

**Comment by kesslerm** [comment]
Checked links on page; these seem to be broken:

http://blog.basho.com/2010/04/27/hello-bitcask/

Not resolved from Markdown:  
[[a REST API]] 
[[Protocol Buffers API]]

http://webmachine.basho.com/ could be a direct link to the github page instead

**Comment by dmitrizagidulin** [comment]
Sounds like we need to change the following links:
1. http://blog.basho.com/2010/04/27/hello-bitcask/ to http://basho.com/hello-bitcask/
2. http://webmachine.basho.com/  to https://github.com/basho/webmachine
3. ```[[a REST API]]``` to ```[[a REST API|http://docs.basho.com/riak/1.1.0/references/apis/http/]]
4. ```[[Protocol Buffers API]]``` to ```[[Protocol Buffers API|http://docs.basho.com/riak/1.1.0/references]]```/apis/protocol-buffers/

**Comment by TheOnlyRew** [comment]
This looks to be fixed. Please reopen if I'm wrong.

**Comment by Basho-JIRA** [comment]
See above comment for resolution. 

***[posted via JIRA by Lauren Rother]***
