### ISSUE TITLE
Add Cloudsoft integration details and links [JIRA: PMT-79]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1567]
Should target branch releases/riak_2.1.0

Waiting for info from CS contact via @seemaj

**Comment by jhmullen** [comment]
From Seema: Create a section on this page  http://docs.basho.com/riak/latest/ops/building/installing/ with Brooklyn Blueprints

**Comment by seemaj** [comment]
Link to Cloudsoft repo: https://github.com/cloudsoft/amp-basho
Use description from Readme to create a blurb on our docs page

**Comment by seemaj** [comment]
Cloudsoft repo link:
https://github.com/cloudsoft/amp-basho

Add link to Cloudsoft repo here:
http://docs.basho.com/riak/latest/dev/advanced/community-projects/#Recipes-Cookbooks-and-Configurations
I also suggest renaming that section to Install and Configure

Add link to Cloudsoft repo here
http://docs.basho.com/riak/latest/ops/building/installing/

Description:
Cloudsoft provides tested, optimized Riak blueprints to help develop and deploy applications faster and easier on a wide range of environments. The AMP-Basho software will automatically deploy and manage Basho Riak and Riak Enterprise clusters using Apache Brooklyn's easy-to-use YAML blueprinting approach, combined with Cloudsoft's enterprise-supported Application Management Platform (AMP).

**Comment by laurenrother** [comment]
@seemaj @jhmullen Was the idea to add a new page under installing (like all the other links there have)? Or just to add a Cloudsoft heading with the description and a link?

**Comment by seemaj** [comment]
Just add the Cloudsoft heading with description and link

**Comment by laurenrother** [comment]
https://github.com/basho/basho_docs/pull/1644
