### ISSUE TITLE
Check/update links for chef/dmg installers [JIRA: PMT-80]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1568]
Should target branch releases/riak_2.1.0

dmg installer content being generated by @drewkerrigan and @glickbot

**Comment by jhmullen** [comment]
Changed title of issue, as Ansible was dropped for Q1

**Comment by jhmullen** [comment]
Changed issue again as Puppet is also dropped for Q1

**Comment by seemaj** [comment]
Add a link to https://github.com/basho-labs/puppet-riak here 
http://docs.basho.com/riak/latest/ops/building/installing/
for the Puppet installer

**Comment by seemaj** [comment]
FYI Chef and Puppet are still at 2.0.5

**Comment by seemaj** [comment]
Chef installer will be updated post release. However, we should remove the page for Chef http://docs.basho.com/riak/latest/ops/building/installing/with-chef/
And just link to the repo here http://docs.basho.com/riak/latest/ops/building/installing/
This needs to be updated for 2.0.5

For the dmg installer we agreed that we will create sections here http://docs.basho.com/riak/latest/quickstart/

1) dmg installer, description of what it is, link to https://github.com/basho-labs/riak-app 
2) devrel installer, description of what it is, link to https://github.com/basho-labs/riak-dev-cluster/
3) rest of instructions as normal to do it the old-fashioned way

**Comment by seemaj** [comment]
We need to update docs when 
1. DMG installer is updated for 2.1 (Drew K)
2. Devrel installer is updated for 2.1 (Tyler)
3. Chef and Puppet are updated for 2.1 (Matt)

**Comment by tylerhannan** [comment]
I will address separately, but updating the [Installing on OS X ](http://docs.basho.com/riak/latest/ops/building/installing/mac-osx/) in the Ops/Building section is probably necessary as well.

Re. Seema's list:

- [x] DMG Installer is updated for 2.1 (Drew K)
- [x] Devrel installer is updated for 2.1 (Tyler)
- [ ] Chef and Puppet are updated for 2.1 (Matt)

**Comment by laurenrother** [comment]
Community installers will be linked in the community section of the docs as we get them. Closing this issue.

**Comment by Basho-JIRA** [comment]
Community installers will get linked in the community section as they come in. 

***[posted via JIRA by Lauren Rother]***
