### ISSUE TITLE
Review and check various client updates [JIRA: PMT-81]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1569]
Client teams are working on branches such as issue #1537 .  These should be reviewed and merged to master.

- .Net -- @lukebakken
  - [x] Docs written
  - [x] Docs merged -- #1537
- PHP -- @cmeiklejohn
  - [ ] Docs written
  - [ ] Docs merged -- #?
- Java -- @broach
  - [ ] Docs written
  - [ ] Docs merged -- #?
- Ruby -- @bkerley
  - [x] Docs written
  - [x] Docs merged -- #?

**Comment by jhmullen** [comment]
This is not a 2.1.0 release requirement so I am removing the [pre-2.1] label.

**Comment by laurenrother** [comment]
Closing this, as either it got done OR it will get caught during the content reorg/edit.
