### ISSUE TITLE
Add links to updated Monitoring repos (zabbix, nagios, new relic) from stats and monitoring page [JIRA: PMT-83]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1571]
Should target branch releases/riak_2.1.0

Note from Seema: be sure to mention that these updates include 2.0 series statistics

- [x] nagios
- [x] zabbix
- [x] new relic

**Comment by jhmullen** [comment]
Nagios is already linked in our monitoring page and only had small vagrantfile updates, so I've checked the box above.  Zabbix and New Relic will need new sections, links, and some light copy.

New links will be:

https://github.com/basho/riak-zabbix
https://github.com/basho/riak_newrelic

**Comment by dmitrizagidulin** [comment]
For the hosted section, let's also add Boundary ( http://www.boundary.com/ ), and DatadogHQ ( https://www.datadoghq.com/integrations/ ).

**Comment by TheOnlyRew** [comment]
Adding information about tools that don't have a 2.1.0 release component didn't feel much like a pre-2.1 task to me, so I created #1582 to capture those additions as a separate task.

**Comment by TheOnlyRew** [comment]
7943384183d88053cee9b7ca73d54ad46d4c2d61 takes a stab at fleshing out some information regarding Zabbix and New Relic, but I'd love a proof-read and maybe a re-wirte before we call the additions good.

**Comment by jhmullen** [comment]
This is underway in PR #1625

**Comment by TheOnlyRew** [comment]
This issue is now complete under #1625.
