### ISSUE TITLE
[pre-2.1] Translate and prepare Riak CS release notes for Riak 2.0 [JIRA: PMT-84]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1572]
Should target branch feature/pre-2.1

**Comment by TheOnlyRew** [comment]
I believe https://github.com/basho/riak_cs/pull/1112, and porting those changes into https://github.com/basho/basho_docs/blob/master/source/languages/en/riakcs/cookbooks/Riak-CS-Release-Notes.md are the last pieces of this puzzle.
