### ISSUE TITLE
Bump Riak Version [JIRA: PMT-85]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1573]
This should target releases/riak_2.1.0 until ready for merge to master.  Should include:

- [x] Add version to `data/versions.yml`
- [x] Change `languages/en.yml` banner
- [x] ~~Add binary links to downloads page~~
- [x] Add release notes to release notes page

**Comment by TheOnlyRew** [comment]
Binary links will be auto-generated, so that's actually a freebie.

**Comment by TheOnlyRew** [comment]
This issue is now complete under #1625.
