### ISSUE TITLE
[pre-2.1] Update CS Compatibility Matrix (Installing-Riak-CS.md and Version-Compatibility.md) to include new versions [JIRA: PMT-89]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1576]
push all changes to feature/pre-2.1

**Comment by TheOnlyRew** [comment]
Confirmed that Riak CS 2.0.0 and Stanchion 2.0.0 are going to be released in parallel with Riak 2.1.0, but CS 2.0.0 is being tested against Riak 2.0.5.

**Comment by TheOnlyRew** [comment]
Updated in 4f574a5aa25474a34392988a3c285f9b996a045f.
