### ISSUE TITLE
Adding / Removing nodes needs info about how to pause / stop [JIRA: PMT-97]

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#1578]
http://docs.basho.com/riak/latest/ops/running/nodes/adding-removing/

A customer wanted to know how to pause or cancel a join or leave.

Pausing can be done by setting transfer-limit to 0, cancellation is not presently possible.
As noted, pausing has other consequences for cluster health and is not recommended for more than a short period of time.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2241 

***[posted via JIRA by Eric Johnson]***
