### ISSUE TITLE
http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/ badly formatted [JIRA: PMT-102]

### ISSUE THREAD

**Issue by kesslerm** [basho/basho_docs#1583]
The configuration example for RedHat / CentOs `/etc/security/limits.conf` is misformatted. The use of numbered lists is inconsistent.

The example has the '*' character at the beginning of the lines in the code block. This seems to interact badly with the whole block being inside a numbered list.

At some point the page seems to have been partly converted from numbered lists to plain paragraphs. The code example would work fine if all of the page was converted to plain paragraphs.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2266 

***[posted via JIRA by Eric Johnson]***
