### ISSUE TITLE
Setting suggestions duplicated in tuning docs [JIRA: PMT-103]

### ISSUE THREAD

**Issue by roooms** [basho/basho_docs#1584]
Overlap and inconsistency of sysctl tcp settings specified twice on the same page at [Storage and File System Tuning](http://docs.basho.com/riak/1.4.12/ops/tuning/linux/#Storage-and-File-System-Tuning) and [Kernel and Network Tuning](http://docs.basho.com/riak/1.4.12/ops/tuning/linux/#Kernel-and-Network-Tuning).

**Comment by laurenrother** [comment]
Please feel free to reopen this issue if the above PR did not address your concerns.
