### ISSUE TITLE
Update Riak CS pages to reflect new configuration options and upgrade steps [JIRA: PMT-107]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1590]
The list below is borrowed from the following Jira issue:  https://bashoeng.atlassian.net/browse/RCS-135#

All changes should target /feature/dpb/riak-cs_configuration_updates

- [x] http://docs.basho.com/riakcs/latest/cookbooks/installing/Installing-Riak-CS/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/Authentication/
- [x] http://docs.basho.com/riakcs/latest/references/apis/storage/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/Using-Riak-CS-With-Keystone/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/ and underlying contents
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Riak/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Stanchion/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Riak-CS/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/configuration-reference/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/logging/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/Rolling-Upgrades-For-Riak-CS/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/multibag/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/garbage-collection/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-MDC/
- [x] http://docs.basho.com/riakcs/latest/cookbooks/Riak-CS-Release-Notes/

**Comment by TheOnlyRew** [comment]
For the Riak-CS-Release-notes, we're just going to be copying the release notes from the [Riak CS repository](https://github.com/basho/riak_cs/blob/develop/RELEASE-NOTES.md) into there correct? So the blocker there is merging the waiting [copy-edits](https://github.com/basho/riak_cs/compare/feature/copy-edit-release-notes-2.1-pre)?

**Comment by TheOnlyRew** [comment]
Also, there additional references to Riak CS's `app.config` in  http://docs.basho.com/riakcs/latest/tutorials/fast-track/Building-a-Local-Test-Environment. The whole fast-track series could use a reasonably substantial re-write, though.

**Comment by TheOnlyRew** [comment]
As Riak CS 2.0.0 has shipped, I'm going to close this issue.
