### ISSUE TITLE
Upgrade Middleman, etc [JIRA: PMT-111]

### ISSUE THREAD

**Issue by jpease** [basho/basho_docs#1595]
We should look at upgrading Middleman and Ruby to 2.2.

This will also likely require updating a few of coderoshi's gems that we use, as they have not been touched in 2 years and have very old dependencies:

* https://github.com/coderoshi/middleman-aws-deploy
* https://github.com/coderoshi/middleman-faqml
* https://github.com/coderoshi/fml

**Comment by dmitrizagidulin** [comment]
Status update:
Resolved/updated the version conflicts in coderoshi's deps (`fml`, `middleman-faqml` and `middleman-aws-deploy`). 
Currently wrestling with `slim` version collision:

```
Bundler could not find compatible versions for gem "tilt":
  In Gemfile:
    slim (~> 1.2.2) ruby depends on
      tilt (~> 1.3.3) ruby

    middleman-faqml (>= 0) ruby depends on
      middleman-core (~> 3.3) ruby depends on
        tilt (< 2.0, ~> 1.4.1) ruby
```
Meaning:
* the latest `middleman-core` (that works with ruby 2.2) wants a later version of [tilt](https://github.com/rtomayko/tilt) (~> 1.4.1). 
* the version of `slim` specified in `basho_docs`'s Gemfile (~> 1.2.2) wants an earlier version of tilt.
* but updating the `slim` version breaks code (doesn't seem to work with the latest version of `middleman`):

```ruby
Slim::Engine: Option :lang is invalid
Slim::Engine: Option :directory_index is invalid
Slim::Parser::SyntaxError: Expected attribute
  /Users/dmitriz/code/Basho/basho_docs/source/languages/en/riak-index.slim, Line 10, Column 18
    li.icon-riak [[Why Riak?|Why Riak]]
                  ^

	/Users/dmitriz/code/Basho/basho_docs/source/languages/en/riak-index.slim:10
	/Users/dmitriz/.rvm/gems/ruby-2.2.0@basho_docs/gems/slim-3.0.3/lib/slim/parser.rb:499:in `syntax_error!'
```
I am currently investigating two options:
1. Debugging the 'invalid option' and syntax error, to see what changed in later versions of Slim (to fix our code).
2. Forking a custom version of slim 1.2.2 that depends on a later `tilt` gem version (and testing to see if that works with latest middleman)

**Comment by dmitrizagidulin** [comment]
After much further investigation and isolation of various gems, the highest version I've been able to upgrade `middleman` to is version 3.0.14 (from our current 3.0.4) -- though for what it's worth, it can be exited with Ctrl-C without having to `kill -9` by that point :)
Correspondingly, I've been able to get `slim` upgraded to 1.3.9

However, bumping Middleman to 3.1 causes our wiki-style links to break (they just show up literal and unprocessed, on the page). Upgrading Slim to 2.0 gives the `Slim::Parser::SyntaxError: Expected attribute` error above.
So, something at the Middleman 3.1 / Slim 2.0 boundary breaks our wiki links (and I haven't been able to figure out the cause in my investigations). 

My recommended point of action at this point is -- let's ask Eric to explain how the wiki-style links on Slim templates are implemented, and why they'd break for Slim 2.0.

**Comment by TheOnlyRew** [comment]
@dmitrizagidulin, the wiki style links were implemented by Eric in the 'lib/sitemap_render_override.rb' file, https://github.com/basho/basho_docs/blob/master/lib/sitemap_render_override.rb#L64-L87. This code is called from `SitemapRenderOverride#process_data!`, which itself is called by the new `::Middleman::Sitemap::Resource#render` method.

All this to say, the Slim template engine has never been responsible for translating double-brackets into links. Slim actually uses `[`, `(`, and `{` as special syntax to [inject attributes (both HTML and Ruby)](http://www.rubydoc.info/gems/slim/frames#Attributes) into the template, so this is either a change to the Slim parser (and how it handles `[[`, `((`, etc.), or may just be an ordering issue where Middleman now waits longer to run its render logic.

One potential solution would be to take advantage of [this PR](https://github.com/slim-template/slim/pull/434) that added the feature of explicitly defining Slim's attribute delimiters, and add the below line to (probably) configure.rb (maybe?)

```ruby
Slim::Engine.set_default_options :attr_delims => {'(' => ')', '{' => '}'}
```

We'd have to check to make sure that the Slim templates we do have don't take advantage of `[` `]` for attribute injection.

If you push your changes to a branch or a fork that I can access, I could test out a few of these changes locally. It might help me see exactly what's going on, or reverse-engineer a couple more of Redmond's additions.

**Comment by dmitrizagidulin** [comment]
@TheOnlyRew Excellent, thank you!
Ok, so, here's my Gemfile changes so far: https://github.com/basho/basho_docs/tree/dz_update_gemfile
with Middleman at 3.0.14 and Slim at 1.3.9
Checkout that branch, and do a `bundle install` (you may actually have to do a `bundle clean --force` first, and then an install).
Note that the wiki-style links work at 3.0.14.
Now bump Middleman to >= 3.1 and do a 'bundle install'. Note that the links don't work (but there's no overt error). Bumping Slim to >= 2.0 is what gives that attribute parsing error.

Now, I've excluded FAQML (both the gem and the handful of FAQ files that use it) from this branch. FAQML has its own problem - upgrading Slim also upgrades the Temple gem to 0.6.10. 
But using the .faqml files with Temple 0.6.10 give the following error:

```
Option :attr_delimiter is not supported by Temple::HTML::AttributeMerger
/Users/dmitriz/.rvm/gems/ruby-2.1.5/gems/temple-0.6.10/lib/temple/html/attribute_remover.rb:10:in `initialize': Option :remove_empty_attrs must be an Array of Strings (ArgumentError)
	from /Users/dmitriz/.rvm/gems/ruby-2.1.5/gems/temple-0.6.10/lib/temple/mixins/engine_dsl.rb:103:in `new'
	from /Users/dmitriz/.rvm/gems/ruby-2.1.5/gems/temple-0.6.10/lib/temple/mixins/engine_dsl.rb:103:in `block in chain_class_constructor'
```
I've temporarily excluded the FAQML gem & files from this investigation because I believe that our main problem is the wiki links. Should we fix those, we can either resolve the FAQML error, or just remove our use of those (and recode the relevant files in .md).

**Comment by TheOnlyRew** [comment]
Okay, I'll dig into this some more when I have time, but it sounds like Middleman 3.1 changes how it munges data during the render phase. My bet is we need to modify the sitemap_render_override.rb file to conform to whatever 3.1 API changes were made.

Thanks for diving this, @dmitrizagidulin!

**Comment by laurenrother** [comment]
Huuuuuuuuuuuuuuuuugoooooooooooooooooooooooooo :clap:
