### ISSUE TITLE
Rolling Replace: add a page for it cause it's great [JIRA: PMT-129]

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#1605]
The steps are as follows:
1. provision one new node of a similar specification to the existing nodes
2. replace the first node in the cluster with the new node
3. wait for the replace transfers to complete and the old node to be automatically removed from the cluster
4. wipe the old node an install riak fresh
5. use the wiped node to replace the next node in the cluster
6. repeat, each node replacing the next, until all nodes have been replaced and only the original new node is left, removed from the cluster last
7. decommission the new node

**Comment by Basho-JIRA** [comment]
Rewrite. 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
http://docs.basho.com/riak/kv/2.2.0/using/repair-recovery/rolling-replaces/ 

***[posted via JIRA by Eric Johnson]***
