### ISSUE TITLE
Taste of Riak and ignoring Riak return codes [JIRA: PMT-134]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1615]
Several of the ToR docs suggest that ignoring the Riak result is OK. This is guaranteed to kill kittens and should be removed from the docs.

**Comment by Basho-JIRA** [comment]
Currently looking through the developing/getting-started docs for the pages in question. 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2438 

***[posted via JIRA by Eric Johnson]***
