### ISSUE TITLE
Refactor the version drop-down to allow scrolling [JIRA: PMT-144]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#1623]
The version drop-down item is getting very close the to bottom of my 1440x900 display, and I'm worried the addition of 2.1.0 and 2.0.6 tags will push the 1.0.0 tag off the bottom of my display. Currently, there's no way to scroll down that bar.

**Comment by laurenrother** [comment]
This is being dealt with/considered https://github.com/basho/private_basho_docs/issues/11
