### ISSUE TITLE
Missing tags for previous releases. [JIRA: PMT-145]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#1628]
It looks like we're missing the release tags for the shipped versions
* 1.0.0
* 1.1.0
* 1.1.4
* 1.4.1
* 1.4.8
* 1.4.9
* 2.0.1

There is no tag for 2.0.0, but there is a branch. Additionally, we have a tag for 1.4.4, but that version isn't deployed on the docs page.

Without the history of those docs pages in git, we can't go back and fix anything in those versions. I'm not sure what the appropriate path forward here should be.

**Comment by laurenrother** [comment]
@theonlyrew Is this an issue that needs to be open in GH/JIRA or is it being now known/documented in the wiki and considered as part of the platform transition?

**Comment by TheOnlyRew** [comment]
This is certainly no longer up to date, and... as the path-forward is currently internal to Basho, I'd say we should close it out, and reopen it -- or something similar -- if necessary.

**Comment by laurenrother** [comment]
Awesome. I added a list item to our transition plan. :)
