### ISSUE TITLE
Rename Five Minute Install to Quick Start [JIRA: PMT-150]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1642]
Five Minute Install is a bit of a misnomer, and should be renamed to quickstart.  This will require some sidebar checking and understanding how the page links are generated, so we will target this after 2.1.0.

**Comment by mjbrender** [comment]
@jhmullen will the URL stay static or be able to redirect? A dead link here is not an option given the amount of sites that link to this here misnomer :smile: 

FYI @tylerhannan

**Comment by jhmullen** [comment]
@mjbrender The various dependencies, external links, etc is the major reason I postponed this to after 2.1.0.  Part of this task will be ensuring that all links work and auto-forward properly.

**Comment by TheOnlyRew** [comment]
the links should be based off of file names, which shouldn't need to change here. We should be able to get away with updating the Title metadata, and all internal links/metadata that references it.
If needs be, we can add a redirect, but needs shouldn't be.

**Comment by mjbrender** [comment]
sounds good all.

**Comment by laurenrother** [comment]
This is part of the content reorg :)
