### ISSUE TITLE
Updates docs with additional tuning guidelines for RHEL [JIRA: PMT-186]

### ISSUE THREAD

**Issue by roooms** [basho/basho_docs#1654]
Meltwater have shared some performance tuning information specific to their deployment, but which could be beneficial as updates to our general tuning guidelines.

http://underthehood.meltwater.com/blog/2015/04/14/riak-elasticsearch-and-numad-walk-into-a-red-hat/

Capturing this here as an issue to make sure we don't lose it. I'll review in more detail and try and get this in to a PR for easy inclusion.

**Comment by laurenrother** [comment]
This is the THP issue and is being dealt with! YAY! https://bashoeng.atlassian.net/browse/RIAK-2127

**Comment by TheOnlyRew** [comment]
If we have a github link we could hand out to users and customers to track this info and its addition to the docs, that be pretty cool to reference here. The Meltwater article remains the best source for now, but having a Basho-branded "We're on the case!" may be valuable.
