### ISSUE TITLE
Ring Size link needs correcting [JIRA: PMT-218]

### ISSUE THREAD

**Issue by jhmullen** [basho/basho_docs#1662]
This page:

http://docs.basho.com/riak/latest/ops/building/configuration/#Ring-Size

References other docs for choosing ring size: "See Planning for a Riak System and Scaling and Operating Riak Best Practices for more details on choosing a ring size."

However these docs don't have ring size help.  This section should link to this page instead:

http://docs.basho.com/riak/latest/ops/building/planning/cluster/#Ring-Size-Number-of-Partitions

**Comment by Basho-JIRA** [comment]
[~seema] Hi Seema, I believe you wanted to double check this is all taken care of. Please move the story forward if it is.  Thanks 

***[posted via JIRA by Patricia Brewer]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/issues/946 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2352 

***[posted via JIRA by Lauren Rother]***
