### ISSUE TITLE
Ring Resize not incompatible with Riak Search 2.0

### ISSUE THREAD

**Issue by ssylvester87** [basho/basho_docs#1742]
The Ring resizing doc: http://docs.basho.com/riak/latest/ops/advanced/ring-resizing/

Says that "Ring resizing cannot be used in clusters using Riak Search 2.0".

This appears to have only been the case with the old-style search from before Riak 2.0/Yokozuna.
The check to see if search is running occurs here:
https://github.com/basho/riak_core/blob/2.1.1/src/riak_core_claimant.erl#L576

Running `app_helper:get_env(riak_search).` on a 2.1.1 node with search enabled returns `{enabled,false}` within its output, which is what it's looking for.

Resizing a ring with search 2.0 enabled happens successfully.

**Comment by Basho-JIRA** [comment]
The ring resize page was removed. 

***[posted via JIRA by Eric Johnson]***
