### ISSUE TITLE
create a redirect so http://docs.basho.com/riak -> http://docs.basho.com/riak/latest/

### ISSUE THREAD

**Issue by binarytemple** [basho/basho_docs#1744]
I've gotten it wrong so many times and hit a 404, sure I'm not the only one.

**Comment by laurenrother** [comment]
Covered here: https://github.com/basho/basho_docs/issues/560 :)

**Comment by Basho-JIRA** [comment]
Duplicate of https://bashoeng.atlassian.net/browse/DOC-48 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
Duplicate of https://bashoeng.atlassian.net/browse/DOC-48 

***[posted via JIRA by Lauren Rother]***
