### ISSUE TITLE
Riak CS 2.0.1 is missing from the Version Compatibility charts

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#1752]
The chart on the below page (and possibly other charts) is missing the CS 2.0.1 version which should be compatible with Riak 2.0.5.

http://docs.basho.com/riakcs/latest/cookbooks/Version-Compatibility/
http://docs.basho.com/riakcs/latest/cookbooks/installing/Installing-Riak-CS/

Consider rolling these charts into one?

**Comment by roooms** [comment]
https://github.com/basho/basho_docs/pull/1763
