### ISSUE TITLE
Broken link to Downloads in Riak Docs v2.1.1

### ISSUE THREAD

**Issue by ph07** [basho/basho_docs#1764]
Page: http://docs.basho.com/riak/2.1.1/ops/building/planning/system-planning/
Search for "If you use [Basho's Riak packages](http://downloads.basho.com/riak/)" - probably should be http://docs.basho.com/riak/2.1.1/downloads/

**Comment by Basho-JIRA** [comment]
I ran a search over the docs and it looks like this line / link is no more 

***[posted via JIRA by Eric Johnson]***
