### ISSUE TITLE
Quickstart and riak-dev-cluster docs/behavior are inconsistent

### ISSUE THREAD

**Issue by danieldreier** [basho/basho_docs#1766]
In http://docs.basho.com/riak/latest/quickstart the instructions call for use of the path `dev1/bin/riak`, `dev2/bin/riak`, `dev3/bin/riak` etc while in https://github.com/basho-labs/riak-dev-cluster/ (which is linked from the quickstart docs) the path created and documented is `riak1/bin/riak`, `riak2/bin/riak`, `riak3/bin/riak` etc.

I'm not sure which is the desired path, but it makes it a little more annoying to follow along the quickstart instructions. Not a huge deal, just a nitpick.

edit: also the port to use for the local HTTP example via curl is 10018 in the quickstart doc, and 11098 in the riak-dev-cluster.

**Comment by Basho-JIRA** [comment]
Since we have killed off QuickStart for now, this no longer applies. 

***[posted via JIRA by Lauren Rother]***
