### ISSUE TITLE
Bitcask capacity planning wording confusing

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#1767]
http://docs.basho.com/riak/latest/ops/building/planning/bitcask/

A customer got confused about "average bucket size". It's really the average size of the bucket names, not the bucket contents. So this wording could be improved.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2385 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
Reviewed and merged. 

***[posted via JIRA by Lauren Rother]***
