### ISSUE TITLE
Incorrect configuration syntax for listeners in Adding/Removing page

### ISSUE THREAD

**Issue by seancribbs** [basho/basho_docs#1772]
Here: http://docs.basho.com/riak/latest/ops/running/nodes/adding-removing/

Listener configuration for `riak.conf` is shown as `listener.http.internal = {"127.0.0.1",8098}` when it should be `listener.http.internal = 127.0.0.1:8098`.

See also https://github.com/basho/cuttlefish/blob/develop/src/cuttlefish_datatypes.erl#L212-L213 and https://github.com/basho/cuttlefish/blob/develop/src/cuttlefish_datatypes.erl#L289-L296 and https://github.com/basho/cuttlefish/blob/develop/src/cuttlefish_datatypes.erl#L279-L284

**Comment by angrycub** [comment]
Fixed and merged...  aww yiss.
