### ISSUE TITLE
MDC v3 documentation should use advanced.config for RiakEE-2.x

### ISSUE THREAD

**Issue by kesslerm** [basho/basho_docs#1776]
The MDC documentation for RiakEE-2 still contains sections that mention the now deprecated `app.config` file. Those should be changed to use `advanced.config` instead.

Examples include

http://docs.basho.com/riak/2.0.6/ops/mdc/v3/configuration/
http://docs.basho.com/riak/2.0.6/ops/mdc/v3/ssl/

**Comment by laurenrother** [comment]
:fish_cake:

**Comment by Basho-JIRA** [comment]
Fixed by Magnus 8/24/15: 
https://github.com/basho/basho_docs/pull/1777
https://github.com/basho/basho_docs/pull/1778
https://github.com/basho/basho_docs/pull/1779
https://github.com/basho/basho_docs/pull/1780 

***[posted via JIRA by Lauren Rother]***
