### ISSUE TITLE
Riak CS Version compatibility matrix is missing our most recent versions

### ISSUE THREAD

**Issue by binarytemple** [basho/basho_docs#1829]
Identified by a customer - the [page](http://docs.basho.com/riakcs/latest/cookbooks/Version-Compatibility/#Working-Version-Combinations) is missing a row for the Riak CS 2.0.1 compatible versions.

**Comment by roooms** [comment]
Fixed in https://github.com/basho/basho_docs/pull/1763 and waiting to go live.
