### ISSUE TITLE
Add section to "Using Data Types" on allow_mult and last_write_wins

### ISSUE THREAD

**Issue by jcapricebasho** [basho/basho_docs#1842]
We need to add a section to [Using Data Types](https://docs.basho.com/riak/2.0.1/dev/using/data-types/) that outlines our requirement for `allow_mult = true` and `last_write_wins = false` on Data Type specific Bucket Types. This section would state the requirement for the above, and briefly explain why the above settings cannot be changed.

**Comment by Basho-JIRA** [comment]
part of: https://github.com/basho/basho_docs/pull/2119

on 2.1.4/developing/data-types page 

***[posted via JIRA by Eric Johnson]***
