### ISSUE TITLE
Inaccurate leveldb's max memory percent setting in cs kv multi backend section [JIRA: DOC-359]

### ISSUE THREAD

**Issue by ksauzz** [basho/basho_docs#1843]
[total_leveldb_mem_percent in riak_cs_kv_multi_backend setting](http://docs.basho.com/riakcs/2.0.1/cookbooks/configuration/Configuring-Riak/#Setting-up-the-Proper-Riak-Backend) is not loaded by eleveldb.

```
        {be_default, riak_kv_eleveldb_backend, [
            {total_leveldb_mem_percent, 30},       <--- this config isn't loaded
            {data_root, "/var/lib/riak/leveldb"}
        ]},
```

Instead, a user has to change `leveldb.maximum_memory.percent` to 30 from 70 in riak.conf:

```
leveldb.maximum_memory.percent = 30
```

or add `total_leveldb_mem_percent` into eleveldb section in advanced.config:

```
{eleveldb, [
  {total_leveldb_mem_percent, 30}
]},
```

**Comment by laurenrother** [comment]
Solved by https://github.com/basho/basho_docs/pull/2040
