### ISSUE TITLE
Typo in http://docs.basho.com/riak/latest/theory/concepts/glossary

### ISSUE THREAD

**Issue by fadushin** [basho/basho_docs#1850]
Spotted a typo at http://docs.basho.com/riak/latest/theory/concepts/glossary/#Node.  I think it should read "Nodes run a certain number of vnodes", not "Nodes run a certain number of nodes".

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2462 

***[posted via JIRA by Eric Johnson]***
