### ISSUE TITLE
Remove obsolete / outdated 'cookbooks' for riakee

### ISSUE THREAD

**Issue by erjohnson** [basho/basho_docs#1853]
[example](http://docs.basho.com/riakee/latest/cookbooks/Multi-Data-Center-Replication-Operations/)

**Comment by laurenrother** [comment]
The Hugo transition did this. 🙌

**Comment by Basho-JIRA** [comment]
Completed by the Hugo transition. 

***[posted via JIRA by Lauren Rother]***
