### ISSUE TITLE
Suggested changes to limits.conf mis-rendered in Open Files Limit doc

### ISSUE THREAD

**Issue by travisbhartwell** [basho/basho_docs#1862]
On http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/ under the heading "Enable PAM-Based Limits for CentOS and Red Hat", the code block for the changes to the /etc/security/limits.conf file are mis-rendered.  A similar block in the section above "Enable PAM-Based Limits for Debian & Ubuntu" is rendered correctly.  Looking at the raw source in source/languages/en/riak/ops/tuning/open-files-limit.md, the only difference between the two is the source block in the CentOS/RH section is indented.

@TheOnlyRew mentioned this might be an issue with Middleman's Markdown parser.

**Comment by TheOnlyRew** [comment]
As #1882 has been merged, can we close this issue?

**Comment by laurenrother** [comment]
Oh, yep. I think not-closing it was just an oversight.
