### ISSUE TITLE
Wrong port in "Building a Local Test Environment"?

### ISSUE THREAD

**Issue by nakanaa** [basho/basho_docs#1864]
In the docs eg. [here](http://docs.basho.com/riakcs/2.1.0/tutorials/fast-track/Building-a-Local-Test-Environment/) it says to change `listener.protobuf.internal` in `riak.conf` to:

```
listener.protobuf.internal = 10.0.2.10:8097
```

And then later on to change `riak_host` in `riak-cs.conf` and `stanchion.conf` to:

```
riak_host = 10.0.2.10:8087
```

But shouldn't this be the one and the same port, eg. **8087**?

In the pre 2.0 docs eg. [here](http://docs.basho.com/riakcs/1.5.4/tutorials/fast-track/Building-a-Local-Test-Environment/) this used to be correct:

```
{http, [ {"10.0.2.10", 8098 } ]}
{pb,   [ {"10.0.2.10", 8087 } ]}
```

**Comment by laurenrother** [comment]
Hi @nakanaa , this looks great! Can you please submit a PR to our repo with this fix?

**Comment by angrycub** [comment]
@nakanaa   Sorry about the confusing commit history.  I branched and added your changes myself.
