### ISSUE TITLE
Update instructions on backing up Riak to include cluster metadata and Riak Search [JIRA: DOC-215]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#1890]
Our documentation regarding backups (see below), do not make mention of how to backup Bucket Types -- Cluster Metadata stored in the `cluster_meta` data directory -- or Riak Search data -- Solr indexes stored in the `yz` data directory. We should discuss their (optional) inclusion in backups.

http://docs.basho.com/riak/latest/ops/running/backups/
http://docs.basho.com/riak/latest/ops/running/recovery/failure-recovery/

**Comment by dmitrizagidulin** [comment]
See also https://github.com/basho-labs/riak-explorer-gui/issues/26

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2276 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
Reviewed. 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
Changes applied to previous versions https://github.com/basho/basho_docs/pull/2276 

***[posted via JIRA by Eric Johnson]***
