### ISSUE TITLE
Rolling upgrade instructions - steps in wrong order [JIRA: DOC-220]

### ISSUE THREAD

**Issue by ssylvester87** [basho/basho_docs#1895]
On this page: http://docs.basho.com/riakee/latest/cookbooks/Rolling-Upgrade-to-Enterprise/

Step 1 and 2 should be reversed. The node should be stopped before backing up the specified directories.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2209 

***[posted via JIRA by Eric Johnson]***
