### ISSUE TITLE
Taste of Riak for NodeJS External Link to GitHub Incorrect [JIRA: DOC-222]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#1897]
On the page: http://docs.basho.com/riak/latest/dev/taste-of-riak/nodejs/ particularly on the last part.. 

```
The Riak Node.js Client has a lot of additional functionality that makes it easy to build rich, complex applications with Riak. Check out the documentation to learn more about working with the Riak Node.js Client and Riak.
```
The `documentation` link goes to the .Net client page in GitHub.

**Comment by Basho-JIRA** [comment]
Looks like this link has been fixed :) 

***[posted via JIRA by Eric Johnson]***
