### ISSUE TITLE
Invalid links to blog articles about vector clocks [JIRA: DOC-228]

### ISSUE THREAD

**Issue by annard** [basho/basho_docs#1921]
On the page [Basic Riak API Operations](https://docs.basho.com/riak/1.2.1/tutorials/fast-track/Basic-Riak-API-Operations/) the links at the bottom of the page that deal with vector clocks are invalid:

http://blog.basho.com/2010/01/29/why-vector-clocks-are-easy/
http://blog.basho.com/2010/04/05/why-vector-clocks-are-hard/

Best regards,
Annard Brouwer

**Comment by laurenrother** [comment]
Hi @annard ! Thanks for the heads up. The 1.2.1 docs are no longer supported, but you can find the blog posts here:
http://basho.com/posts/technical/why-vector-clocks-are-easy/
http://basho.com/posts/technical/why-vector-clocks-are-hard/

You may also be interested in the recent follow-up to those classic posts: 
http://basho.com/posts/technical/vector-clocks-revisited/
http://basho.com/posts/technical/vector-clocks-revisited-part-2-dotted-version-vectors/
