### ISSUE TITLE
missing an arity in riakc_pb_socket:create_search_index [JIRA: DOC-235]

### ISSUE THREAD

**Issue by janevin** [basho/basho_docs#1930]
In the Sets Example of page basho_docs/source/languages/en/riak/dev/search/search-data-types.md,
the Erlang sample code of creating search index is missing an arity:
riakc_pb_socket:create_search_index(Pid, <<"hobbies">>, <<"_yz_default">>).
It should be 
riakc_pb_socket:create_search_index(Pid, <<"hobbies">>, <<"_yz_default">>, []).

And the same thing for Maps Example
riakc_pb_socket:create_search_index(Pid, <<"customers">>, <<"_yz_default">>).
should be 
riakc_pb_socket:create_search_index(Pid, <<"customers">>, <<"_yz_default">>, []).

**Comment by Basho-JIRA** [comment]
part of: https://github.com/basho/basho_docs/pull/2119

on 2.1.4/developing/usage/searching-data-types 

***[posted via JIRA by Eric Johnson]***
