### ISSUE TITLE
CRDT counter docs should mention no context is used / needed [JIRA: DOC-236]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1931]
https://docs.basho.com/riak/2.1.3/dev/using/data-types/#Data-Types-and-Context

The docs should mention that CRDT counters do not use context, ever.

See basho/riak-python-client#426

**Comment by Basho-JIRA** [comment]
part of: https://github.com/basho/basho_docs/pull/2119

found on the 2.1.4/developing/data-types page under the Data Types and Context heading. 

***[posted via JIRA by Eric Johnson]***
