### ISSUE TITLE
Add additional advanced.config documentation [JIRA: DOC-250]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#1951]
http://docs.basho.com/riak/latest/ops/advanced/configs/configuration-files/#Advanced-Configuration

Inspired by this thread on riak-users:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2016-February/018089.html

**Comment by TheOnlyRew** [comment]
May relate to
#1936
#1843
#1827
#1630
#1593

**Comment by lukebakken** [comment]
Awesome, thanks @TheOnlyRew
