### ISSUE TITLE
Do not call `riak-admin vnode-status` on frequent intervals [JIRA: DOC-252]

### ISSUE THREAD

**Issue by jenagraham** [basho/basho_docs#1959]
We should add a note to the `riak-admin vnode-status` documentation on the [vnodes page][0] that mentions you should not run this command on an interval more frequent than every 5 minutes.  Running it more often that that will result in handoffs being stalled.  

For more in-depth technical detail, this is a problem because when you run riak-admin vnode-status it sends a message to the vnode to gather the requested information. The message looks no different to the vnode than messages that are client or other cluster work. A vnode will only be considered idle when the receive loop times out. By default this timeout is set to 60 seconds. When a vnode hits that timeout a message is sent to the vnode_manager to say that it is idle. Once a vnode is idle, then finally at that point a partition handoff process could be kicked off.

[0]:  http://docs.basho.com/riak/latest/theory/concepts/vnodes/#Vnode-Status

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2243 

***[posted via JIRA by Eric Johnson]***
