### ISSUE TITLE
Time Series Included? [JIRA: DOC-261]

### ISSUE THREAD

**Issue by paultannenbaum** [basho/basho_docs#1962]
I was going through the Riak TS docs and noticed a couple of typos. I only see riak-kv and riak-s2 docs, no time series. Could somebody point me in the right direction?

**Comment by laurenrother** [comment]
@paultannenbaum Do you mean in the basho_docs repo? You can find the most recent TS docs here: https://github.com/basho/basho_docs/tree/riakts/1.2.0/source/languages/en/riakts
Or you can link the pages in a comment here and I'll fix them :)

**Comment by laurenrother** [comment]
Fixed by this: https://github.com/basho/basho_docs/pull/1983

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/1983 

***[posted via JIRA by Lauren Rother]***
