### ISSUE TITLE
Object Update example in Erlang should use update_value rather than update [JIRA: DOC-263]

### ISSUE THREAD

**Issue by jenagraham** [basho/basho_docs#1964]
In the Basic Usage, Object Updates section of the documentation there is an [example][0] on how to update an object.  The Erlang version currently reads:
```
update_coach(team, new_coach) ->
    {ok, Obj} = riakc_pb_socket:get(Pid,
                                    {<<"siblings">>, <<"coaches">>},
                                    <<team>>),
    ModifiedObj = riakc_obj:update(Obj, <<new_coach>>),
    riakc_pb_socket:put(Pid, ModifiedObj).

%% Example usage
update_coach('packers', 'Vince Lombardi')
```
It should be updated to use the `update_value` function rather than the `update` function.  I do not think there was ever an `update` function in the Erlang client and does not exist in any recent versions.  The Taste of Riak Erlang Client Version correctly uses `update_value`.

Thanks!

[0]:  http://docs.basho.com/riak/latest/dev/using/updates/#Example-Update

**Comment by Basho-JIRA** [comment]
http://docs.basho.com/riak/kv/2.1.4/developing/usage/updating-objects/#example-update

the second example for that section 

***[posted via JIRA by Eric Johnson]***
