### ISSUE TITLE
Description about the error message: `too_many_subqueries` [JIRA: DOC-268]

### ISSUE THREAD

**Issue by ksauzz** [basho/basho_docs#1966]
`too_many_subqueries` error happens when a user hit the limitation of `timeseries_query_max_quanta_span`. Although the docs already represents this error as `too many sub-queries`, docs should also include the explicit error message:  `too_many_subqueries`.

http://docs.basho.com/riakts/1.2.0/using/querying/
http://docs.basho.com/riakts/1.2.0/using/configuring/

**Comment by Basho-JIRA** [comment]
Fixed by  https://github.com/basho/basho_docs/commit/4b09c965815ec6d5f828a112cd845e94247605f1 

***[posted via JIRA by Lauren Rother]***
