### ISSUE TITLE
Include a note in the Install chapter stating that Debian is only supported for developing with Riak TS [JIRA: DOC-270]

### ISSUE THREAD

**Issue by dannylauca** [basho/basho_docs#1968]
In the page (http://docs.basho.com/riakts/latest/installing/mac-osx) of the Riak TS 1.2 docs, there is a note stating that Mac OS X is only supported for developing with Riak TS.  A similar note should appear on the page (http://docs.basho.com/riakts/latest/installing/debian-ubuntu) for Debian.

**Comment by Basho-JIRA** [comment]
Fixed by: https://github.com/basho/basho_docs/commit/99a04c29ab78494895d0e87d6df16395f38ca198 

***[posted via JIRA by Lauren Rother]***
