### ISSUE TITLE
Trusty download of Riak CS 2.1.1 is broken [JIRA: DOC-275]

### ISSUE THREAD

**Issue by roooms** [basho/basho_docs#1971]
Hash is missing and when clicking the link it returns access denied.

http://docs.basho.com/riakcs/latest/riakcs-downloads/

**Comment by laurenrother** [comment]
@coughlan @ooshlablu I think this is something only your team can fix?

**Comment by TheOnlyRew** [comment]
This is fixed as of the Hugo release.
