### ISSUE TITLE
Riak TS doc corrections and improvements [JIRA: DOC-277]

### ISSUE THREAD

**Issue by dannylauca** [basho/basho_docs#1975]
This is sort of a catch-all issue that sums up corrections and suggestions that I found while using the Riak TS docs to develop the training material.

- On all platforms, the limit on the number of open file handles need to be increased to at least 65536.  Otherwise, Riak will not start up.  In most cases, this requires adding the following lines to the /etc/security/limits.conf file and then rebooting the system:

*               soft     nofile          65536
*               hard    nofile          65536

I suggest adding this to the installation pages for the individual platforms such as http://docs.basho.com/riakts/latest/installing/rhel-centos/#Install-Riak-TS since the mechanism to increase the limit may vary among platforms.

- The "yum install” command for CentOS/RHEL needs to be updated to reference the latest version of Riak TS.  It currently says 1.0.0.  See  http://docs.basho.com/riakts/1.2.0/installing/rhel-centos.

- On all platforms, there is no need to turn off AAE because the riak.conf file already has anti_entropy set to passive out of the box.  Therefore, the “Turn off AAE” section should be removed from all platform-specific installation pages.

- The Riak TS node should not be started until after configuring riak-shell.  Therefore, the “Activate Riak TS Node” should be removed from all platform-specific installation pages.

- On pages such as http://docs.basho.com/riakts/latest/using/planning which reference SQL statements and syntax, keywords such as NOT NULL, TIMESTAMP and QUANTUM should all be capitalized to distinguish them from tokens such as table and column names.

- Move the section “Using riak_shell” to near the front of the “Using Riak TS” chapter since we should emphasize the use of this command-line utility to perform tasks more efficiently than using API function calls.  Also, the name of the utility is “riak-shell”, not “riak_shell”.  That needs to be changed in several areas of http://docs.basho.com/riakts/latest/using/riakshell.

- The name of the configuration file for riak-shell is riak_shell.config and resides in the /etc/riak directory.  This needs to be corrected/clarified in http://docs.basho.com/riakts/latest/using/riakshell.  Also, we should recommend that the user update the nodename, listener.http.internal and listener.protobuf.internal settings in the riak.conf file, and the cluster_mgr setting in the advanced.config file since the default IP address is 127.0.0.1 (localhost).  The IP address needs to be changed if a user is planning to set up a multi-node cluster.  After all the configuration files have been updated, the user can then start the Riak TS node.

- We should emphasize issuing the CREATE TABLE statement through riak-shell rather than using “riak-admin bucket-type create” as shown in http://docs.basho.com/riakts/latest/using/creating-activating.  Even though the underlying construct of a table is a bucket type, I’m not sure if we need to mention this Riak KV concept as it is more of an implementation detail in Riak TS.  Also, by using CREATE TABLE, the underlying bucket-type is automatically activated.

- When the INSERT statement is available, we should emphasize the use of it in http://docs.basho.com/riakts/latest/using/writingdata.  Examples of API calls to perform operations such as writes and reads should be moved to the individual API sections such as http://docs.basho.com/riakts/latest/developing/erlang where the corresponding functions are introduced and described.

- Emphasize issuing SELECT statements through riak-shell in http://docs.basho.com/riakts/latest/using/querying.  The API examples should be moved to the individual API sections.

- The sections on aggregate functions and arithmetic operations should be moved to just after the “Querying Data in Riak TS” section.

**Comment by Basho-JIRA** [comment]
TS doc updates reported in following issues have been completed:

https://github.com/basho/basho_docs/issues/1968

https://github.com/basho/basho_docs/issues/1975 

***[posted via JIRA by Danny Lau]***
