### ISSUE TITLE
leveldb repair doc needs to include a tiered storage example [JIRA: DOC-278]

### ISSUE THREAD

**Issue by matthewvon** [basho/basho_docs#1976]
http://docs.basho.com/riak/2.0.5/ops/running/recovery/repairing-leveldb/

The above page needs a second example for repairing a tiered storage vnode.  Basically add these two lines to the configuration:

{tiered_slow_prefix,"/slow_mount"},
      {tiered_fast_prefix,"/fast_mount"},

**Comment by matthewvon** [comment]
ok, some better info:

The current repair doc help contains this:

[application:set_env(eleveldb, Var, Val) || {Var, Val} <- 
    [{max_open_files, 2000}, 
     {block_size, 1048576}, 
     {cache_size, 20*1024*1024*1024}, 
     {sync, false}, 
     {data_root, ""}]].

max_open_files, block_size, cache_size, and sync lines are not needed so:

[application:set_env(eleveldb, Var, Val) || {Var, Val} <- 
    [{data_root, ""}]].

is sufficient.

Next comment will give same for tiered storage scenario.

**Comment by roooms** [comment]
@matthewvon do you have an update or code snippet for this issue? I am working on some other improvements to this page and would like to get your suggested changes in as well. Your last comment says...

> Next comment will give same for tiered storage scenario.

Thanks,
Dan

**Comment by matthewvon** [comment]
Reasonable question.  No I have not gone back to research for cleanup.  Uh, let me see how the morning goes here.  I remember the issue and need to test against samples of Riak 2.2.0 to be sure I give accurate info.

Matthew

**Comment by matthewvon** [comment]
First, need to consider the existing tiered storage doc.  It only mentions 3 variables, it should mention 4.  Example:

leveldb.data_root=data_root
leveldb.tiered=2
leveldb.tiered.path.fast=/var/db/fast_mount
leveldb.tiered.path.slow=/var/db/slow_mount

Riak constructs the resulting storage paths as follows:

leveldb.tiered.path.fast "/" leveldb.data_root "/" vnode_name
leveldb.tiered.path.slow "/" leveldb.data_root "/" vnode_name

Sow vnode "0"s paths are:

/var/db/fast_mount/data_root/0
/var/db/slow_mount/data_root/0

The user must manually create the paths preceding the vnode_name on the mounts: i.e. /var/db/fast_mount/data_root and /var/db/slow_mount/data_root must exist prior to starting Riak.

**Comment by matthewvon** [comment]
Sadly, riak.conf uses slightly different naming than app.config and repair's config.  The variables the user needs to set for repair are

[application:set_env(eleveldb, Var, Val) || {Var, Val} <- 
[{data_root, ""}]].

**Comment by matthewvon** [comment]
This line likely has to change too (going to have to ask around):

eleveldb:repair("/path-to-vnode/<vnode_number>", []).

**Comment by roooms** [comment]
That's useful to know as I aim to make that command and the surrounding notes less ambiguous. At the moment it is not clear if this should target the `/var/lib/riak/leveldb/<vnode_number>` directory or the `/var/lib/riak/kv_vnode/<vnode_number>` directory.

**Comment by matthewvon** [comment]
Ok, here is what we really need (because set_env() is not working properly with repair() ):

Options = [{tiered_slow_level, 2},
{tiered_fast_prefix, "/var/db/fast_mount"},
{tiered_slow_prefix, "/var/db/slow_mount"}].

eleveldb:repair("<data_root>/<vnode_number>", Options).

non-tiered storage should ignore Options and set_env.  Simply:

eleveldb:repair("/path-to-vnode/<vnode_number>", []).

**Comment by matthewvon** [comment]
<data_root> being the data_root from app.config or riak.conf  ... which defaults to "$platform_data_dir/leveldb" in cuttlefish ... where $platform_data_dir default to "./data".

**Comment by matthewvon** [comment]
Summary:  
1. Tiered storage configuration page should now included "data_root" variable.

2. Repair needs to drop set_env stuff because currently useless.

3. Repair needs second example for tiered storage repair using the Options variable to simplify repairing multiple vnodes.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2439/ 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2464 

***[posted via JIRA by Lauren Rother]***
