### ISSUE TITLE
Add clarification to developing/data-types/#flags-within-maps [JIRA: DOC-316]

### ISSUE THREAD

**Issue by laurenrother** [basho/basho_docs#2028]
Per [this issue](https://github.com/basho/riak-erlang-client/issues/279#issuecomment-212519507), we could use additional, clearer docs here.

From riak channel at irc.freenode.net
> russelldb: the client is opinionated here, 'cos the api at riak allows that operation, but potentially unsafe

Would be great if this is described in documentation.
[Flags Within Maps](http://docs.basho.com/riak/kv/2.1.4/developing/data-types/#flags-within-maps)

**Comment by nerophon** [comment]
Same page, different anchor:
http://docs.basho.com/riak/kv/2.1.4/developing/data-types/#data-types-and-context

There's no http example here, and a customer asked for it. The actual example code is here:
http://docs.basho.com/riak/kv/2.1.4/developing/usage/updating-objects/#using-causal-context

... in other words the documentation is repeated, but I think this is a good thing in this case.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2119 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2119 

***[posted via JIRA by Eric Johnson]***
