### ISSUE TITLE
404 links on docs [JIRA: DOC-317]

### ISSUE THREAD

**Issue by jouerose** [basho/basho_docs#2032]
hi. 

on this page: http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/
the following links at least are not working (404):
http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/developing/getting-started/golang/
http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/developing/getting-started/java/
in fact all the links to for official drivers are not working: ruby, python, erlang....

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2036 

***[posted via JIRA by Eric Johnson]***

**Comment by laurenrother** [comment]
Hi @jouerose ! Thanks for pointing those out. The above PR should fix them. :)
