### ISSUE TITLE
incorrect path for planning link [JIRA: DOC-318]

### ISSUE THREAD

**Issue by oliryde** [basho/basho_docs#2033]
There is a link to the planning page with an incorrect path. The path ends up as /installing/using/planning but it looks like it should be /using/planning/.
This issue is present on http://docs.basho.com/riak/ts/1.2.0/installing/debian-ubuntu/ including all versions and operating systems.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2034 

***[posted via JIRA by Eric Johnson]***
