### ISSUE TITLE
1.4.12 bad link in downloads page [JIRA: DOC-358]

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#2039]
http://docs.basho.com/riak/1.4.12/downloads/

Under the RHEL packages is this line:
"Here are further instructions for Installing on RHEL and CentOS"
It contains a link which goes here:
http://docs.basho.com/riak/1.4.12/ops/building/installing/rhel-centos/

But that page shows a 500 error.

**Comment by TheOnlyRew** [comment]
So, 500 is an Internal Server error. I'm not sure what would cause CloudFront to throw that error, or S3 to prevent CF from accessing a page.
To confuse me further, http://docs.basho.com/riak/1.4.12/ops/building/installing/rhel-centos/ resolves correctly for me.

Can anyone else confirm the 500 error?

**Comment by laurenrother** [comment]
I tried both going to /ops/building/installing/rhel-centos directly and via the link @nerophon gave above and I got no errors/the page resolved correctly. 

Super weird.
