### ISSUE TITLE
Broken link to RHEL install instructions [JIRA: DOC-366]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#2044]
http://docs.basho.com/riak/kv/2.1.4/downloads/#red-hat-enterprise-linux-6

The link directs to installing/rhel/ when it should direct to installing/rhel-centos/

This link will need to be corrected in data/os-meta.yaml.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2052 

***[posted via JIRA by Lauren Rother]***
