### ISSUE TITLE
Clarify immutable data use cases [JIRA: DOC-367]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#2047]
The documentation should be very clear that immutable data is not a use-case for CRDTs. The docs mislead a user into thinking that CRDTs would be a good use-case in the following manner:

----

Tracing my steps back, I think I was looking at application guide here - the main missing key seems to be missing mention of "write-once" feature (which is mentioned somewhere else):
http://docs.basho.com/riak/kv/2.1.4/developing/app-guide/#good-fits-for-riak

Here is how it went in my case (to the best recollection of my faulty memory - caveat emptor):
- Check how to model immutable data - looked at riak notes above
- Read the first one mentioning immutable data.
- Read the last one mentioning "Data compatible with Riak Data Types"
- Since my data is compatible with Riak data type, let us model it as CRDT. Checked the guide above once again to see if it mentions anything about CRDT and immutability kind of being mutually exclusive cases. It didn't.
- Then, I checked this section, and it seemed it was ok to have immutable CRDT:
http://docs.basho.com/riak/kv/2.1.4/developing/app-guide/#when-not-to-use-riak-data-types
- After that, when I checked this, it seemed to be strongly recommending CRDT since my data types fit (just registers):
http://docs.basho.com/riak/kv/2.1.4/developing/app-guide/#when-to-use-riak-data-types
Especially this part which convinced me it is ok to have CRDT: Most things that can be stored as JSON, for example, can be stored as maps (though with modifications).

**Comment by angrycub** [comment]
@lukebakken, do you feel like the changes in https://github.com/basho/basho_docs/issues/2122 address your concerns here, or does this need additional work?

**Comment by lukebakken** [comment]
@angrycub looks great, thanks

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2122 

***[posted via JIRA by Lauren Rother]***
