### ISSUE TITLE
KV 2.1.4 doesn't support spark connector. [JIRA: DOC-368]

### ISSUE THREAD

**Issue by ksauzz** [basho/basho_docs#2051]
We should remove [spark connector docs](http://docs.basho.com/riak/kv/2.1.4/add-ons/spark-riak-connector/) from KV 2.1.4 pages, which could lead to misunderstanding. It only works with TS and BDP now.

**Comment by Basho-JIRA** [comment]
[~jgorlick][~phardak][~mdigan]

Is this true? If so I can remove the section from KV 2.1.4

https://bashoeng.atlassian.net/browse/DOC-253 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
[~jgorlick] [~phardak] [~mdigan]

Is this true? If so I can remove the section from KV 2.1.4

https://bashoeng.atlassian.net/browse/DOC-253 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
Yes, it is written in Spark Connector docs:
{quote}
*Compatibility*
* Riak TS 1.2+
* Apache Spark 1.6+
* Scala 2.10
* Java 8
*Coming Soon*
** Support for Riak KV 2.2 and later{quote}
 

***[posted via JIRA by Pavel Hardak]***

**Comment by Basho-JIRA** [comment]
Yes, it is written in Spark Connector docs:
{quote}
*Compatibility*
* Riak TS 1.2+
* Apache Spark 1.6+
* Scala 2.10
* Java 8
*Coming Soon*
* Support for Riak KV 2.2 and later
{quote}
 

***[posted via JIRA by Pavel Hardak]***

**Comment by Basho-JIRA** [comment]
Yes, it is written in Spark Connector docs:
{quote}
*Compatibility*
* Riak TS 1.2+
* Apache Spark 1.6+
* Scala 2.10
* Java 8
*Coming Soon*
* Support for Riak KV 2.2 and later
{quote}

I am not sure why it was changed to Riak KV 2.1+ when migrated to Riak KV...  

***[posted via JIRA by Pavel Hardak]***

**Comment by Basho-JIRA** [comment]
Also - I do not understand how people writing Spark apps are going to know that KV buckets are supported in Riak TS. 
Do we have any decisions or guidelines about that? This issue is not only about Spark, but for any other operation (get, set, del, 2i, MR, ..) 

***[posted via JIRA by Pavel Hardak]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2054 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
[~ejohnson] - please make sure this info is accessible from TS 1.3, as Spark allows operations with KV-buckets in Riak TS 1.3 and this is supported functionality. 

***[posted via JIRA by Pavel Hardak]***
