### ISSUE TITLE
Precommit hook is not called for write_once buckets [JIRA: DOC-375]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#2076]
This document should note that the `precommit` property (and probably `postcommit`) is ignored for bucket types where `write_once` is `true`:

https://docs.basho.com/riak/kv/2.1.4/developing/app-guide/write-once/

**Comment by macintux** [comment]
Both are ignored.

**Comment by sanketr** [comment]
It will be good to also have an explanation of why this exception to the rule in the case of "write_once" buckets.

**Comment by lukebakken** [comment]
@sanketr - we'll add that, but in short, it is a performance optimization.

**Comment by angrycub** [comment]
Closed by https://github.com/basho/basho_docs/pull/2116
