### ISSUE TITLE
Malformed link to default bucket-type doc [JIRA: DOC-376]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#2077]
![dev-usage-creating-objects-link-error](https://cloud.githubusercontent.com/assets/514926/15299574/d7c0aa10-1b59-11e6-9cf4-b0dbe408411c.png)

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2091 

***[posted via JIRA by Eric Johnson]***
