### ISSUE TITLE
Download anchors are "undefined" [JIRA: DOC-385]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#2084]
Page:

http://docs.basho.com/riak/kv/2.1.4/downloads/

Clicking on "Riak KV for Ubuntu" returns this link:

http://docs.basho.com/riak/kv/2.1.4/downloads/#undefined

I expected an anchor for that particular download. Thanks!

**Comment by TheOnlyRew** [comment]
Hmm... This looks to be an unintended side-effect of #2066. I think I see the issue and the fix. Will have a PR up soon.

**Comment by TheOnlyRew** [comment]
Fixed by #2086

The fix hasn't been deployed, but I'ma close this issue anyway.

**Comment by Basho-JIRA** [comment]
See linked PR for resolution 

***[posted via JIRA by Lauren Rother]***
