### ISSUE TITLE
Riak-TS Erlang Client Put Documentation [JIRA: DOC-405]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2103]
As per client request, please revise the wordings on the documentation for the Erlang client PUT command in the Riak-TS documentation http://docs.basho.com/riak/ts/1.3.0/developing/erlang/

Please see request below (ZD 13668): 

> Using RiakTS 1.3.0 and riak-erlang-client 2.3.0-timeseries, 
Please revise in the following documentation "a list of values" to read "a tuple of values".

> Reference: 
http://docs.basho.com/riak/ts/1.3.0/developing/erlang/ 
Function Details put/3

> Also, Please revise the following sample code as tuples.

> Reference: 
https://github.com/basho/riak-erlang-client/blob/2.3.2-timeseries/README.md 
Store TS Data

**Comment by lukebakken** [comment]
See the following:

* basho/riak-erlang-client#302

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/commit/aef4ccbdffe0772348bdf00758a04ad7f2917cef 

***[posted via JIRA by Lauren Rother]***
