### ISSUE TITLE
Bad Link - concepts/active-anti-entropy "configuration file" [JIRA: DOC-431]

### ISSUE THREAD

**Issue by zeeshanlakhani** [basho/basho_docs#2121]
The link at the bottom of http://docs.basho.com/riak/kv/2.1.4/learn/concepts/active-anti-entropy/#active-anti-entropy-and-hash-tree-exchange should point to http://docs.basho.com/riak/kv/2.1.4/configuring/reference/#active-anti-entropy or, at least, the configuration reference.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2244 

***[posted via JIRA by Eric Johnson]***
