### ISSUE TITLE
docs website has links to localhost [JIRA: DOC-433]

### ISSUE THREAD

**Issue by packetopsphone** [basho/basho_docs#2124]
On this page:
http://docs.basho.com/community/productadvisories/

The link:
Potential data loss on restart with LevelDB tiered storage

Links to:
http://localhost:1313/community/productadvisories/leveldbrestart/

**Comment by erjohnson** [comment]
https://github.com/basho/basho_docs/commit/4d6675314fa4bcb63dfbd09c11682cc56b67ca05

**Comment by laurenrother** [comment]
![](http://vignette2.wikia.nocookie.net/pacificrim/images/0/09/Homer-Simpson-wingnuts-doh.gif)

Thanks for pointing this out @packetopsphone .
