### ISSUE TITLE
Documentation missing parameter for UpdateMap.Builder()  [JIRA: DOC-449]

### ISSUE THREAD

**Issue by Rilussion** [basho/basho_docs#2141]
The code in this section - http://docs.basho.com/riak/kv/2.1.4/developing/usage/document-store/#storing-blog-posts-as-maps needs to be corrected.

The second parameter is missing in the below line of code:

UpdateMap storeBlogPost = new UpdateMap.Builder(location, mapUpdate)
            .build();

**Comment by Rilussion** [comment]
Fix merged. Closing issue

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2142 

***[posted via JIRA by Lauren Rother]***
