### ISSUE TITLE
Riak TS Command to Untar Incomplete [JIRA: DOC-454]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2150]
http://docs.basho.com/riak/ts/1.3.0/installing/mac-osx/

It just says .tar .. while the archive for download is .tar.gz

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/commit/1bfbaacff92b48b3a382fb940da1ae7ade62cc89 

***[posted via JIRA by Lauren Rother]***
