### ISSUE TITLE
Sample Code Consistency [JIRA: DOC-458]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2156]
http://docs.basho.com/riak/ts/1.3.0/using/writingdata/#writing-data

I was going through the sample code due to a ticket im working on using Erlang. I have added some sample values but I decided to switch to PHP so I could code faster. After fumbling all around, I noticed that the sample code are a bit different across programming languages. (ie. sample values, using 10017 vs 8087, time format). 

I was hoping we could have standard values so that people trying out the example would not end up with different stuff stored in the data if they are trying out a different programming language.

**Comment by Basho-JIRA** [comment]
We're going to undertake this work as part of the 1.4 release, specifically focusing on streamlining the ports in all sample code to be 8098 and 8087 (which are actual default ports). 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
currently working on this. 

***[posted via JIRA by Eric Johnson]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/private_basho_docs/pull/223 

***[posted via JIRA by Eric Johnson]***
