### ISSUE TITLE
Additional Notes/Reminders in Cloning Client Libraries [JIRA: DOC-459]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2157]
For Riak TS http://docs.basho.com/riak/ts/1.3.0/developing/

I suggest adding additional instructions to make sure that the one being cloned from the repository of the client libraries are the ones tagged with Riak TS. 

This occurred to me following the instructions on the individual README.md pages for several clients like Python and PHP and failed to clone the correct branch with TS support.

**Comment by Basho-JIRA** [comment]
Thanks [~aortile]! I double checked with the Clients team and all the TS support have been merged into the main branch of each project, and thanks to another ticket asking for links to each client repo, each page has a direct link now :) Let me know if we need to update anything else to make this easier.  

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
[~lrother] thanks Lauren, I will perform several tests cloning from the main branch then do some TS functions. greatly appreciate the work done.  

***[posted via JIRA by Allan Paul Ortile]***
