### ISSUE TITLE
Riak TS create table page needs examples [JIRA: DOC-461]

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#2162]
A customer was confused because this page:

http://docs.basho.com/riak/ts/1.3.1/using/creating-activating/

...has no examples. It should probably have one for each client. The C# example can be taken from the convenience function here:

https://github.com/basho/riak-dotnet-client/blob/develop/src/Test/Integration/TS/TimeseriesTests.cs#L169

**Comment by laurenrother** [comment]
@nerophon We opted to link out to the Creating section in the client-specific docs to avoid duplicating too much information (and thus needing to update in two places). (See http://docs.basho.com/riak/ts/1.3.1/using/creating-activating/#create-table-query-in-client-library)

I'm 100% open to adding these in to the page, but I want to be clearer about why the linking doesn't work.

**Comment by Basho-JIRA** [comment]
Commit: https://github.com/basho/private_basho_docs/commit/c9a472671814e6e1cff790c755e22b9de0724548

PR: https://github.com/basho/private_basho_docs/pull/266 

***[posted via JIRA by Lauren Rother]***

**Comment by Basho-JIRA** [comment]
Merged (y) 

***[posted via JIRA by Eric Johnson]***
