### ISSUE TITLE
Ensure Cloud Front serves compressed files [JIRA: DOC-478]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#2175]
This will require finishing the TODO [here](https://github.com/basho/basho_docs/blob/72213117473ed63a5ca38eb42d2d6d4b84ebbbaf/libs/basho_rake_deploy.rb#L273-L274) and ensuring that Cloud Front is configured to automatically gzip content as per http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by TheOnlyRew** [comment]
This task has been completed.

**Comment by Basho-JIRA** [comment]
Hat tip to [~phagan] and [~ccoughlan] for helping me set this up. 

***[posted via JIRA by Drew Pirrone-Brusse]***
