### ISSUE TITLE
Active Entropy Configuration File Link Goes to Incorrect Page [JIRA: DOC-489]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2200]
http://docs.basho.com/riak/kv/2.1.4/learn/concepts/active-anti-entropy/#active-anti-entropy-and-hash-tree-exchange

Clicking on the `configuration file` like goes to http://docs.basho.com/riak/kv/2.1.4/configuring/v3-multi-datacenter/

**Comment by Basho-JIRA** [comment]
duplicate of: https://bashoeng.atlassian.net/browse/DOC-431 

***[posted via JIRA by Eric Johnson]***
