### ISSUE TITLE
Erlang docs for single key fetch wrong [JIRA: DOC-493]

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#2205]
http://docs.basho.com/riak/ts/1.3.1/using/querying/#single-key-fetch requires an empty 4th argument to get for the Erlang example

```erlang
riakc_ts:get(Pid, <<"GeoCheckin">>, [<<"South Atlantic">>, <<"South Carolina">>, 1420113600000], []).
```

This has apparently been true since day 1, so please feel free to update all of the versions.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/private_basho_docs/commit/2fb1f754a5a8dc493b7f86bae920f278e13ea812 

***[posted via JIRA by Lauren Rother]***
