### ISSUE TITLE
CSS Issues with scrolling code blocks followed by headers [JIRA: DOC-602]

### ISSUE THREAD

**Issue by angrycub** [basho/basho_docs#2218]
Reported by @Geolim4,  When scrolling code blocks are followed by a header class object, you can not use the horizontal scroll bar.  I verified that this is due to the negative margin in the header class creating the header object above the scrollbar component.

I was able to reproduce the issue on Chrome and Firefox 48 (the browser reported)

http://docs.basho.com/riak/kv/2.1.4/setup/installing/debian-ubuntu/
![issue_screen_shot](https://cloud.githubusercontent.com/assets/464492/17973103/1a8c4756-6aaf-11e6-9a3f-1f0afa994e93.png)

**Comment by Geolim4** [comment]
Indded, in fact even the code itself is not easily copyable.

**Comment by TheOnlyRew** [comment]
This issue will be resolved with #2226.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2226 

***[posted via JIRA by Lauren Rother]***
