### ISSUE TITLE
Rebar3 warning message ''Insecure HTTPS request..please update to OTP 17.4" [JIRA: DOC-603]

### ISSUE THREAD

**Issue by Keam** [basho/basho_docs#2220]
Hi, I'm using Erlang R16B02_basho10.  I received this message when I do the following...

``$ rebar3 local upgrade``
``$ ==> Insecure HTTPS request (peer verification disabled), please update to OTP 17.4 or later
``

How do I update my current version on Ubuntu 16.04? I installed via 

``wget http://s3.amazonaws.com/downloads.basho.com/erlang/otp_src_R16B02-basho8.tar.gz``

I can't find any guidance on 

``http://docs.basho.com/riak/kv/2.1.4/setup/installing/source/erlang/#installing-on-debian-ubuntu``

Thank you!

**Comment by laurenrother** [comment]
Hi @Keam , it looks like you've got a rebar3 problem, which means we're not going to know how to help you. I suggest going here: https://www.rebar3.org/discuss and seeing what they say.

Good luck!
