### ISSUE TITLE
incorrect link on 2.1.4/learn/concepts/active-anti-entropy/  [JIRA: DOC-658]

### ISSUE THREAD

**Issue by russelldb** [basho/basho_docs#2246]
Half way down the page the paragraph

> Although AAE is enabled by default, it can be turned off if necessary. See our documentation on managing active anti-entropy information on how to enable and disable AAE, as well as on configuring and monitoring AAE.

The link at "See our documentation on managing active anti-entropy" points to the page http://docs.basho.com/riak/kv/2.1.4/using/cluster-operations/v3-multi-datacenter/

Should it point to a page about managing active anti-entropy, maybe http://docs.basho.com/riak/kv/2.1.4/using/cluster-operations/active-anti-entropy/?

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2368 

***[posted via JIRA by Lauren Rother]***
