### ISSUE TITLE
Erroneous NAT information in CRDT pages [JIRA: DOC-700]

### ISSUE THREAD

**Issue by TheOnlyRew** [basho/basho_docs#2274]
Erroneous mostly because it shouldn't be there.

The bad information is present on all data-types/maps.md pages 2.0.0 thorugh 2.1.4.
http://docs.basho.com/riak/kv/2.1.4/developing/data-types/maps/#client-setup

It looks like the NAT information was added during a scripted change of "bucket-types" to "bucket types". It should be removed.

**Comment by TheOnlyRew** [comment]
Opened in response to customer ticket number 14127

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2275 

***[posted via JIRA by Lauren Rother]***

**Comment by kesslerm** [comment]
This issue has resurfaced in the currently deployed docs site.

**Comment by TheOnlyRew** [comment]
Thanks for bringing this back up, @kesslerm. It's been re-resolved with #2446 and #2447.
