### ISSUE TITLE
Cluster Administration > riak-admin CLI > ensemble-status [JIRA: DOC-705]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2282]
The URL title for `Managing Strong` is incomplete. Should be `Managing Strong Consistency`

http://docs.basho.com/riak/kv/2.1.4/using/admin/riak-admin/#ensemble-status

**Comment by pogzie** [comment]
Changes have been merged. Closing this issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2295 

***[posted via JIRA by Lauren Rother]***
