### ISSUE TITLE
Cluster Administration > riak-admin CLI > describe [JIRA: DOC-707]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2284]
The describe command example is inconsistent with the output. http://docs.basho.com/riak/kv/2.1.4/using/admin/riak-admin/#describe

`riak-admin describe nodename` has the following output: 

```
nodename:
  Name of the Erlang node
```

While the example output is from the command: `riak-admin describe ring_size`.

Either change the example command or the example output.

**Comment by pogzie** [comment]
Changes have been merged. Closing this issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2295 

***[posted via JIRA by Lauren Rother]***
