### ISSUE TITLE
Cluster Administration > riak CLI > config [JIRA: DOC-709]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2286]
The sample output for `riak config describe storage_backend` has changed from the current example. 

The new format describes the valid values such as this line: 

```
  Valid Values: 
     - one of: bitcask, leveldb, memory, multi, prefix_multi
```

While the old example shows it as a Datatype: 

```
Datatype     : [{enum,[bitcask,leveldb,memory,multi]}]
```

**Comment by pogzie** [comment]
Changes have been merged. Closing this issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2295 

***[posted via JIRA by Lauren Rother]***
