### ISSUE TITLE
Cluster Operations > Changing Cluster Info > Change the HTTP [JIRA: DOC-710]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2287]
Loose `"` on the third code sample (protocol buffer interface).

```
listener.protobuf.internal = 0.0.0.0":8087
```

http://docs.basho.com/riak/kv/2.1.4/using/cluster-operations/changing-cluster-info/#change-the-http-and-protocol-buffers-binding-address

**Comment by pogzie** [comment]
Changes have been merged. Closing this issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2295 

***[posted via JIRA by Lauren Rother]***
