### ISSUE TITLE
Getting Started > PHP > CRUD Operations > Updating Objects In Riak [JIRA: DOC-712]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2290]
Missing `$` on the PHP variable named `object3`. 

```
object3 = $response3->getObject();
$data3 = $object3->getData();
```

**Comment by pogzie** [comment]
Changes have been merged. Closing this issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2295 

***[posted via JIRA by Lauren Rother]***
