### ISSUE TITLE
Two docs discuss restore from backup in different ways, we should settle on one. [JIRA: DOC-714]

### ISSUE THREAD

**Issue by nerophon** [basho/basho_docs#2293]
The information in /repair-recovery/failure-recovery is incorrect, but the information in /cluster-operations/changing-cluster-info/ is correct. So let's replace the incorrect one with a link to the correct one.

**Comment by Basho-JIRA** [comment]
Fixed by: https://github.com/basho/basho_docs/pull/2292 

***[posted via JIRA by Lauren Rother]***
