### ISSUE TITLE
Formatting Problem in Using > Cluster Administration > riak CLI [JIRA: DOC-722]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2308]
http://docs.basho.com/riak/kv/2.2.0/using/admin/riak-cli/ 

The recently pushed changes were reflected properly in the preview of the document but was misshapen when its rendered on the docs.basho.com site.

**Comment by angrycub** [comment]
Fixed in #2321

**Comment by Basho-JIRA** [comment]
Fixed by Charlie in PR linked in above comment 

***[posted via JIRA by Lauren Rother]***
