### ISSUE TITLE
Upgrading to Riak KV 2.2.0 > Data File Format Changes [JIRA: DOC-728]

### ISSUE THREAD

**Issue by pogzie** [basho/basho_docs#2319]
Add or include a footer information to explain what Automatic, Required and Upgrade Only means. It confused some of our users. 

Reference ticket #14234

**Comment by angrycub** [comment]
Fixed in #2320

**Comment by Basho-JIRA** [comment]
Fixed by Charlie in PR linked above. 

***[posted via JIRA by Lauren Rother]***
