### ISSUE TITLE
HTTP list buckets doesn't give bucket type example [JIRA: DOC-753]

### ISSUE THREAD

**Issue by lukebakken** [basho/basho_docs#2337]
http://docs.basho.com/riak/kv/2.2.0/developing/api/http/list-buckets/

We should add an example of listing buckets in a type.

See this ML thread:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2016-December/018879.html

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2339 

***[posted via JIRA by Lauren Rother]***
