### ISSUE TITLE
Ambiguous documentation of `extract/1` in custom extractor interface [JIRA: DOC-770]

### ISSUE THREAD

**Issue by lucafavatella** [basho/basho_docs#2347]
Custom extractor [doc](https://github.com/basho/basho_docs/blob/c89bccc102113b6325485fadaa0b5bb4e7ef9320/content/riak/kv/2.2.0/developing/usage/custom-extractors.md#the-extractor-interface) documents `extract/1` in the following way:
> extract/1 --- Takes the contents of the object and returns the same contents and an empty list

... then gives an example that implements such function as the following equivalent code:
```
extract(Value) ->
    [{text, Value}].
```

... that does not resemble the description of `extract/1` above.

I also looked at a real extractor for reference, the [CRDT one](https://github.com/basho/yokozuna/blob/3f556dcba91757c5c7c0a67990b9cfeb5034d5ea/src/yz_dt_extractor.erl#L80), and the spec of `extract/1` does not make sense with the definition in the doc above.

I am not sure how the correct doc would look like so I am not opening PR with proposal - just opening this ticket for tracking.

**Comment by angrycub** [comment]
Thanks for the report @lucafavatella.  Does PR #2350 address your concerns?

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2350 

***[posted via JIRA by Lauren Rother]***

**Comment by lucafavatella** [comment]
> Thanks for the report @lucafavatella. Does PR #2350 address your concerns?

@angrycub Yes, perfect. Thanks.
