### ISSUE TITLE
Unreadable rendered page "PBC Data Type Fetch" [JIRA: DOC-776]

### ISSUE THREAD

**Issue by lucafavatella** [basho/basho_docs#2365]
The bottom part of [page "PBC Data Type Fetch"](http://docs.basho.com/riak/kv/2.2.0/developing/api/protocol-buffers/dt-fetch/#optional-parameters) is not readable because covered by panel on the left (tried on Firefox and Safari).

I had a look at the source but it all looks [ok](https://github.com/basho/basho_docs/blob/6b2f42a7243bfded737bd62eed12c490376c67e2/content/riak/kv/2.2.0/developing/api/protocol-buffers/dt-fetch.md#optional-parameters) so I think the issue sits in the markdown -> HTML renderer.

Inspecting the HTML reveals that it looks like the bottom content is pushed out of the main `div role="main"` and `article class="mainarticle"`. Maybe the table confuses the renderer. You might double check pages with similar structure as they may suffer from similar issue.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/basho_docs/pull/2367 

***[posted via JIRA by Lauren Rother]***
