### ISSUE TITLE
where can I find the goog.csv file mentioned in the docs basho riak 1.2.0 tutorial? [JIRA: DOC-854]

### ISSUE THREAD

**Issue by michalstepniewski** [basho/basho_docs#2466]
where can I find the goog.csv file mentioned in the docs basho riak 1.2.0 tutorial?

**Comment by alexmoore** [comment]
Hi, 

I think it's the same one we provide in the much newer docs:

http://docs.basho.com/riak/kv/2.2.0/developing/app-guide/advanced-mapreduce/#bigger-data-examples

https://raw.githubusercontent.com/basho/basho_docs/master/extras/data/goog.csv

Thanks,
Alex

**Comment by angrycub** [comment]
@michalstepniewski,  if you happen to be using 1.2.0, I would definitely encourage you to upgrade as Riak KV 1.2.0 is _very_ _very_ legacy.
