### ISSUE TITLE
http://docs.basho.com is broken

### ISSUE THREAD

**Issue by kevinkl** [basho/basho_docs#2517]
http://docs.basho.com is broken. 

A "403 Forbidden" error gets thrown, when you want to access it.

Detailed error message:
- Code: AllAccessDisabled
- Message: All access to this object has been disabled

**Comment by russelldb** [comment]
Basho is in receivership, Tiot.jp have kindly mirrored the docs here https://www.tiot.jp/riak-docs/

**Comment by kevinkl** [comment]
Thanks for the fast response!
