### ISSUE TITLE
Add redirect - /riak/ to point to /riak/latest/, fix sidebar nav on 404 [JIRA: PMT-176]

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho/basho_docs#560]
Minor request (to make navigation via url chopping easier):

Right now, http://docs.basho.com/riak/ gets a 404.
(the correct link is http://docs.basho.com/riak/latest/ ).

But even worse, once you hit that 404 page, none of the links on the left sidebar nav work.
So, two requests:
1. Add a rewrite rule /riak/ -> /riak/latest/  (and /riakcs/ -> /riakcs/latest/, and /riakee/)

2. If possible, fix the sidebar nav so that landing on a 404 page does not disable navigation to the rest of the site.

**Comment by DSomogyi** [comment]
Import to Jira.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
Noting that this is being worked on as part of the platform transition plan. https://github.com/basho/private_basho_docs/issues/11

**Comment by laurenrother** [comment]
Hugo work solves this.
