### ISSUE TITLE
Update Couchbase Comparison [JIRA: PMT-175]

### ISSUE THREAD

**Issue by coderoshi** [basho/basho_docs#588]
Right now the Riak to Couchbase comparison doc is showing its age. It was written before Couchbase was really a thing, and we basically compared their conjecture against our reality. Now that

1) Riak is older, some of the Riak points need to change
2) Couchbase is 2.1, we should compare that against our 1.4.1

http://docs.basho.com/riak/latest/theory/comparisons/couchbase/

I'm marking this as a bug, because it's currently just wrong

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by binarytemple-bet365** [comment]
Page no longer exists, time to close this issue.

**Comment by Basho-JIRA** [comment]
We removed the page during the side nav reorg/Hugo transition. 

***[posted via JIRA by Lauren Rother]***
