### ISSUE TITLE
Once a bad URL is entered, it's hard to escape [JIRA: PMT-174]

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#607]
I tried using http://docs.basho.com/riak/latest/dev/, and discovered once I was at that broken link, all of the left sidebar links were relative to that broken link, so I quickly ended up at http://docs.basho.com/riak/latest/dev/dev/references/http/dev/references/protocol-buffers/, for example.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
Duplicate of https://github.com/basho/basho_docs/issues/1623
