### ISSUE TITLE
Mobile docs view is underpowered [JIRA: PMT-173]

### ISSUE THREAD

**Issue by macintux** [basho/basho_docs#628]
On an iPhone or iPad there is no way (that I can find) to see the content navigation or change Riak versions. I imagine there's already a ticket about this but I don't see it.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by TheOnlyRew** [comment]
In the top-right corner of e.g. http://docs.basho.com/riak/latest/, there is (on my Android, leastwise) a little grey button with three horizontal bars. pressing that will open a view into the navigation menu.

That said, if it's not discoverable, it needs work.

Also, it's... pretty ugly.

**Comment by Basho-JIRA** [comment]
This task is being folded in with a redesign of our CSS. It may not be completed as part of the first round of CSS wok, but it will be heavily considered. 

***[posted via JIRA by Drew Pirrone-Brusse]***

**Comment by Basho-JIRA** [comment]
Docs on mobile are much better and more flexible than before. 

***[posted via JIRA by Lauren Rother]***
