### ISSUE TITLE
Update Dynamo comparison  [JIRA: PMT-171]

### ISSUE THREAD

**Issue by PharkMillups** [basho/basho_docs#651]
Primarily to reflect:

- DynamoDB's ability to do [periodic snapshot copying across regions](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-crossregion-ddb.html)
- DynamoDB's 64k object size limit 

I'll take a stab at this later this week.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
Please feel free to reopen this issue if it still stands.
