### ISSUE TITLE
Configuring Riak Control in 2.0.0

### ISSUE THREAD

**Issue by angrycub** [basho/basho_docs#862]
This is an interesting beast because we stopped packaging the sample SSL certs, so now people have to generate their own.  I've done some real roughcut documentation on generating self-signed ssl certs (also useful for security, but Luke's SSL Cert tutorial is much more robust than mine) and the riak.conf settings necessary to enable config.

https://gist.github.com/angrycub/964d48d429a3e8180798

Just wanting to file the issue so I can close a ticket
-cv

**Comment by lucperkins** [comment]
Addressed in PR #1497
