### ISSUE TITLE
Document ring_size / n_val / physical node combinations where resilience promises break down [JIRA: PMT-168]

### ISSUE THREAD

**Issue by jaredmorrow** [basho/basho_docs#946]
See https://github.com/basho/riak/issues/381  we should document these in the ring_size section of the docs.  I searched around and didn't see any mention (though it has been mentioned a ton in the riak-users mailing list).

Closing the basho/riak issue in favor of this one.

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by laurenrother** [comment]
Fixed by: https://github.com/basho/basho_docs/pull/2352
